classdef JsonTreeView
    % JsonTreeView  Reusable JSON tree viewer built on uihtml.
    %
    %   Renders any MATLAB struct / cell / numeric value as a collapsible,
    %   syntax-highlighted JSON tree. The first level is expanded by default;
    %   deeper levels can be drilled into interactively. A small toolbar
    %   provides "Expand all", "Collapse all", and "Copy JSON" actions.
    %
    %   Usage:
    %     % Build (returns a uihtml handle you can store on the app)
    %     viewer = JsonTreeView.attach(parent);
    %
    %     % Populate with a struct / cell / any jsonencode-able value
    %     JsonTreeView.setData(viewer, myStruct);
    %
    %     % Or show a plain status message (when there is no JSON to view)
    %     JsonTreeView.setMessage(viewer, 'Dashboard refreshed from session state.');
    %
    %   Notes:
    %     - Data is passed through jsonencode to avoid MATLAB struct/cell
    %       quirks on the JS side.
    %     - The HTMLSource is self-contained: no external CSS/JS dependencies.

    methods (Static)

        function h = attach(parent)
            % attach  Build the uihtml viewer inside `parent` and return the handle.
            h = uihtml(parent);
            h.HTMLSource = JsonTreeView.htmlTemplate();
            h.Data = struct('kind', 'empty');  % initial state
        end

        function setData(h, value)
            % setData  Render `value` as a JSON tree.
            if isempty(h) || ~isvalid(h); return; end
            try
                jsonStr = jsonencode(value);
            catch ME
                JsonTreeView.setMessage(h, sprintf('Unable to encode JSON: %s', ME.message));
                return;
            end
            h.Data = struct('kind', 'json', 'json', jsonStr);
        end

        function setMessage(h, text)
            % setMessage  Show a plain status message (replaces the tree).
            if isempty(h) || ~isvalid(h); return; end
            h.Data = struct('kind', 'message', 'text', char(text));
        end
    end

    methods (Static, Access = private)

        function src = htmlTemplate()
            % htmlTemplate  Self-contained HTML/CSS/JS for the tree viewer.
            %
            % The JS listens for DataChanged and renders one of three kinds:
            %   {kind:'empty'}                    — default placeholder
            %   {kind:'message', text:'...'}      — plain text status line
            %   {kind:'json', json:'...'}         — JSON tree (string payload)
            pieces = [ ...
"<!doctype html><html><head><meta charset='utf-8'><style>" ...
"html,body{margin:0;padding:0;height:100%;background:#ffffff;" ...
"font-family:'SF Mono','Menlo','Consolas','Courier New',monospace;font-size:12px;" ...
"color:#1f2937;}" ...
".toolbar{display:flex;align-items:center;gap:6px;padding:4px 8px;border-bottom:1px solid #e5e7eb;" ...
"background:#f9fafb;font-family:system-ui,'Segoe UI',sans-serif;font-size:11px;color:#4b5563;" ...
"position:sticky;top:0;z-index:10;}" ...
".toolbar button{font:inherit;background:#ffffff;border:1px solid #d1d5db;border-radius:4px;" ...
"padding:3px 8px;cursor:pointer;color:#374151;}" ...
".toolbar button:hover{background:#eef2ff;border-color:#a5b4fc;color:#1e3a8a;}" ...
".toolbar .spacer{flex:1;}" ...
".toolbar .meta{color:#6b7280;font-size:10px;}" ...
".tree{padding:8px 10px;overflow:auto;height:calc(100% - 30px);box-sizing:border-box;}" ...
".msg{padding:14px;color:#4b5563;font-family:system-ui,'Segoe UI',sans-serif;font-size:12px;" ...
"white-space:pre-wrap;line-height:1.5;}" ...
".row{line-height:1.55;white-space:pre;}" ...
".toggle{display:inline-block;width:12px;color:#6b7280;cursor:pointer;user-select:none;text-align:center;}" ...
".toggle.leaf{color:transparent;cursor:default;}" ...
".key{color:#2563eb;}" ...
".punct{color:#9ca3af;}" ...
".str{color:#047857;}" ...
".num{color:#b45309;}" ...
".bool{color:#7c3aed;font-weight:600;}" ...
".null{color:#6b7280;font-style:italic;}" ...
".badge{color:#6b7280;font-size:10px;margin-left:6px;font-family:system-ui,'Segoe UI',sans-serif;}" ...
".children{padding-left:16px;border-left:1px dotted #e5e7eb;margin-left:3px;}" ...
".children.collapsed{display:none;}" ...
".preview{color:#9ca3af;font-size:11px;margin-left:6px;}" ...
".empty{padding:14px;color:#9ca3af;font-style:italic;}" ...
"</style></head><body>" ...
"<div class='toolbar'>" ...
"<button id='btn-expand'  title='Expand all'>Expand all</button>" ...
"<button id='btn-collapse' title='Collapse all'>Collapse all</button>" ...
"<button id='btn-copy'    title='Copy JSON to clipboard'>Copy JSON</button>" ...
"<span class='spacer'></span>" ...
"<span id='meta' class='meta'></span>" ...
"</div>" ...
"<div id='root' class='tree'></div>" ...
"<script>" ...
"function setup(comp){" ...
"var root=document.getElementById('root');" ...
"var meta=document.getElementById('meta');" ...
"var currentJson='';" ...
"function esc(s){return String(s).replace(/[&<>]/g,function(c){return c==='&'?'&amp;':c==='<'?'&lt;':'&gt;';});}" ...
"function preview(v){" ...
"if(Array.isArray(v))return '['+v.length+']';" ...
"if(v&&typeof v==='object')return '{'+Object.keys(v).length+'}';" ...
"if(typeof v==='string')return v.length>40?JSON.stringify(v.slice(0,40))+'…':JSON.stringify(v);" ...
"if(v===null)return 'null';return String(v);}" ...
"function renderValue(v){" ...
"if(v===null)return '<span class=""null"">null</span>';" ...
"var t=typeof v;" ...
"if(t==='string')return '<span class=""str"">'+esc(JSON.stringify(v))+'</span>';" ...
"if(t==='number'||t==='bigint')return '<span class=""num"">'+esc(String(v))+'</span>';" ...
"if(t==='boolean')return '<span class=""bool"">'+esc(String(v))+'</span>';" ...
"return esc(String(v));}" ...
"function isContainer(v){return v&&typeof v==='object';}" ...
"function renderNode(key,value,depth,isLast){" ...
"var div=document.createElement('div');div.className='node';" ...
"var row=document.createElement('div');row.className='row';" ...
"var toggle=document.createElement('span');toggle.className='toggle';" ...
"var keyHtml=key==null?'':('<span class=""key"">'+esc(JSON.stringify(key))+'</span><span class=""punct"">: </span>');" ...
"if(isContainer(value)){" ...
"var isArr=Array.isArray(value);" ...
"var count=isArr?value.length:Object.keys(value).length;" ...
"toggle.textContent=depth<1?'▾':'▸';" ...
"var opener=isArr?'[':'{';var closer=isArr?']':'}';" ...
"row.appendChild(toggle);" ...
"var header=document.createElement('span');" ...
"header.innerHTML=keyHtml+'<span class=""punct"">'+opener+'</span>'+" ...
"'<span class=""badge"">'+count+(isArr?' item'+(count===1?'':'s'):' key'+(count===1?'':'s'))+'</span>';" ...
"row.appendChild(header);" ...
"var children=document.createElement('div');children.className='children';" ...
"if(depth>=1)children.classList.add('collapsed');" ...
"var keys=isArr?value.map(function(_,i){return i;}):Object.keys(value);" ...
"keys.forEach(function(k,i){children.appendChild(renderNode(isArr?null:k,isArr?value[k]:value[k],depth+1,i===keys.length-1));});" ...
"var close=document.createElement('div');close.className='row';" ...
"close.innerHTML='<span class=""toggle leaf""> </span><span class=""punct"">'+closer+(isLast?'':',')+'</span>';" ...
"toggle.addEventListener('click',function(){" ...
"var coll=children.classList.toggle('collapsed');" ...
"toggle.textContent=coll?'▸':'▾';" ...
"if(coll){" ...
"var prev=header.querySelector('.preview');if(prev)prev.remove();" ...
"var p=document.createElement('span');p.className='preview';p.textContent=' '+preview(value);header.appendChild(p);" ...
"}else{var prev2=header.querySelector('.preview');if(prev2)prev2.remove();}" ...
"});" ...
"if(depth>=1){" ...
"var p2=document.createElement('span');p2.className='preview';p2.textContent=' '+preview(value);header.appendChild(p2);" ...
"}" ...
"div.appendChild(row);div.appendChild(children);div.appendChild(close);" ...
"}else{" ...
"toggle.classList.add('leaf');toggle.textContent=' ';" ...
"row.appendChild(toggle);" ...
"var leaf=document.createElement('span');" ...
"leaf.innerHTML=keyHtml+renderValue(value)+'<span class=""punct"">'+(isLast?'':',')+'</span>';" ...
"row.appendChild(leaf);div.appendChild(row);" ...
"}" ...
"return div;}" ...
"function renderTree(obj){" ...
"root.innerHTML='';" ...
"if(obj===null||obj===undefined){root.innerHTML='<div class=""empty"">No data.</div>';meta.textContent='';return;}" ...
"if(typeof obj!=='object'){root.appendChild(renderNode(null,obj,0,true));meta.textContent='1 value';return;}" ...
"var keys=Array.isArray(obj)?obj:Object.keys(obj);" ...
"meta.textContent=(Array.isArray(obj)?obj.length+' items':Object.keys(obj).length+' keys');" ...
"root.appendChild(renderNode(null,obj,0,true));}" ...
"function expandAll(flag){" ...
"root.querySelectorAll('.children').forEach(function(c){" ...
"if(flag){c.classList.remove('collapsed');}else{c.classList.add('collapsed');}});" ...
"root.querySelectorAll('.toggle').forEach(function(t){" ...
"if(t.classList.contains('leaf'))return;" ...
"t.textContent=flag?'▾':'▸';});" ...
"if(!flag){root.querySelectorAll('.node > .row > span:nth-child(2)').forEach(function(h){" ...
"var old=h.querySelector('.preview');if(old)old.remove();});}}" ...
"document.getElementById('btn-expand').addEventListener('click',function(){expandAll(true);});" ...
"document.getElementById('btn-collapse').addEventListener('click',function(){expandAll(false);});" ...
"document.getElementById('btn-copy').addEventListener('click',function(){" ...
"try{navigator.clipboard.writeText(currentJson||'');" ...
"var b=this;var t=b.textContent;b.textContent='Copied';setTimeout(function(){b.textContent=t;},1000);}catch(e){}});" ...
"function apply(d){" ...
"if(!d){root.innerHTML='<div class=""empty"">Awaiting data…</div>';meta.textContent='';currentJson='';return;}" ...
"if(d.kind==='message'){root.innerHTML='<div class=""msg"">'+esc(d.text||'')+'</div>';meta.textContent='';currentJson='';return;}" ...
"if(d.kind==='empty'){root.innerHTML='<div class=""empty"">Awaiting data…</div>';meta.textContent='';currentJson='';return;}" ...
"if(d.kind==='json'){" ...
"currentJson=d.json||'';" ...
"try{var obj=JSON.parse(currentJson);renderTree(obj);}" ...
"catch(e){root.innerHTML='<div class=""msg"">Invalid JSON: '+esc(e.message)+'</div>';meta.textContent='';}" ...
"}}" ...
"comp.addEventListener('DataChanged',function(){apply(comp.Data);});" ...
"apply(comp.Data);" ...
"}" ...
"</script></body></html>"];
            src = char(strjoin(pieces, ""));
        end
    end
end
