classdef HelpContent
    % HelpContent  Per-screen help text + HTML renderer for the in-app
    %                "?" help dialog.
    %
    %   bodyFor(key) returns a struct with five fields:
    %     .purpose      one-sentence elevator pitch
    %     .doesText     bullet-list of what the screen does
    %     .measurements bullet-list of measured / displayed values
    %     .formulas     line-per-formula technical block
    %     .notes        gotchas, references, caveats
    %
    %   renderHtml(displayName, body) wraps the struct into a styled
    %   HTML page suitable for a uihtml component inside the help
    %   dialog (DialogBuilder.buildScreenHelpDialog).
    %
    %   To extend: add a new `case` arm in bodyFor for the routing key
    %   and follow the existing five-field schema.

    methods (Static)

        function s = bodyFor(key)
            % bodyFor  Return the help struct for a screen routing key.
            %   Unknown keys fall through to a generic "no help yet"
            %   stub so the dialog still opens.
            switch char(key)
                case 'Dashboard'
                    s = struct( ...
                        'purpose', ['Default landing screen after login — at-a-glance health and ' ...
                                    'next-step suggestions for the active project.'], ...
                        'doesText', [ ...
                            '• KPI strip (circuits / jobs / backends / completed runs).' newline ...
                            '• Clickable workflow stepper that mirrors the recommended pipeline.' newline ...
                            '• Run Readiness 4-cell layout (circuit selected, backend selected,' newline ...
                            '  benchmark configured, prediction done).' newline ...
                            '• Backend Health summary across the live IBM fleet.' newline ...
                            '• Job Submissions trend (last 14 days).' newline ...
                            '• Merged Activity feed — UI events + job records, with right-click context menu.' newline ...
                            '• Smart Next-Step CTA that adapts to the current pipeline stage.' newline ...
                            '• Project switcher in toolbar; 30-second silent auto-refresh.'], ...
                        'measurements', [ ...
                            '• Project counts (total / favourites / recently active).' newline ...
                            '• Job counts by state (queued, running, completed, failed).' newline ...
                            '• Backend availability state per IBM Quantum endpoint.' newline ...
                            '• Activity-event volume (last 24 h / 7 d).'], ...
                        'formulas', '— Not applicable.', ...
                        'notes', [ ...
                            'Auto-refresh fires every 30 s without overlay flicker. Right-click ' ...
                            'an activity row for context-menu actions (open job, open report, ' ...
                            'dismiss). Empty-state hero card replaces the dashboard for projects ' ...
                            'with no activity yet.']);

                case 'Welcome'
                    s = struct( ...
                        'purpose', ['Login, project picker, and recent-projects shortcut. ' ...
                                    'The sidebar shows this as "Projects" — the routing key ' ...
                                    'stays "Welcome" for back-compat.'], ...
                        'doesText', [ ...
                            '• Authenticates the user against the QTAU Connector backend (bearer token).' newline ...
                            '• Lists every project the active user can access.' newline ...
                            '• New project / Edit project / Delete project actions.' newline ...
                            '• Recently-opened shortcut for one-click re-entry.' newline ...
                            '• On successful login, auto-navigates to the Dashboard.'], ...
                        'measurements', [ ...
                            '• Per-project metadata: created_at, updated_at, role, member count.'], ...
                        'formulas', '— Not applicable.', ...
                        'notes', [ ...
                            'Roles are enforced server-side via /api/projects/{id}/* — the UI ' ...
                            'only hints at access; the API is the source of truth.']);

                case 'Circuits'
                    s = struct( ...
                        'purpose', ['Browse, search, and manage every circuit in the active ' ...
                                    'project.'], ...
                        'doesText', [ ...
                            '• Paginated table with qubits, depth, gate counts, source label, last modified.' newline ...
                            '• Toolbar Composer (✎) — open the in-app gate editor on a blank slate.' newline ...
                            '• Toolbar Upload (↑) — import a .qasm file with format selection.' newline ...
                            '• Right-click a row for Analyze / Predict / Cut / Delete actions.' newline ...
                            '• Free-text search across circuit names + tags.'], ...
                        'measurements', [ ...
                            '• num_qubits, depth, gate-count vector (1Q / 2Q / measurement / barrier).' newline ...
                            '• Source label (User / QTAUBench / MQTBench / Composer).' newline ...
                            '• Upload timestamp.'], ...
                        'formulas', '— Not applicable.', ...
                        'notes', [ ...
                            'The standalone Upload screen is hidden from the sidebar — the ' ...
                            'Upload button on this toolbar is its canonical entry point. ' ...
                            'QTAUBench-sourced circuits come from the 252-circuit corpus ingested ' ...
                            'from PNNL QASMBench.']);

                case 'Composer'
                    s = struct( ...
                        'purpose', ['In-app circuit authoring with click-to-place gates and ' ...
                                    'a bidirectional OpenQASM 2.0 mirror.'], ...
                        'doesText', [ ...
                            '• Click-to-place gate palette: H / X / Y / Z / S / T / S† / T† /' newline ...
                            '  Rx / Ry / Rz / reset / CX / CZ / SWAP / CCX / M / barrier.' newline ...
                            '• Wire canvas on uiaxes; ± qubit buttons add / remove a wire.' newline ...
                            '• Bidirectional QASM mirror — editing the textbox re-renders the canvas.' newline ...
                            '• 12-template gallery: Bell, GHZ_n, QFT_n, Grover_k, Bernstein–Vazirani_n,' newline ...
                            '  Deutsch–Jozsa_n, Phase Estimation, VQE H₂, QAOA, Trotter, Teleport, Superdense.' newline ...
                            '• Inspect footer with local statevector simulator (≤14 qubits):' newline ...
                            '  step slider, Bloch ⟨X⟩/⟨Y⟩/⟨Z⟩ tile per qubit, top-K amplitude bars, ▶ Auto-step.' newline ...
                            '• 📤 Export modal — OpenQASM 2, OpenQASM 3, Qiskit, Cirq, Braket Python.' newline ...
                            '• 📦 Bundle modal — one-click reproducibility ZIP (circuit + metadata + calibration' newline ...
                            '  snapshot + mitigation estimates + FT estimate + README + manifest.json with SHA-256).'], ...
                        'measurements', [ ...
                            '• ⟨X⟩, ⟨Y⟩, ⟨Z⟩ Bloch coordinates per qubit.' newline ...
                            '• Top-K amplitude magnitudes |c_i|² for the dominant basis states.'], ...
                        'formulas', [ ...
                            '• Statevector evolution: |ψ⟩ = U_n · … · U_2 · U_1 · |0…0⟩.' newline ...
                            '• Reduced density matrix: ρ_i = Tr_{j≠i} |ψ⟩⟨ψ|.' newline ...
                            '• Bloch vector: (⟨X⟩, ⟨Y⟩, ⟨Z⟩) = (Tr(ρ_i·X), Tr(ρ_i·Y), Tr(ρ_i·Z)).'], ...
                        'notes', [ ...
                            'Local simulator capped at 14 qubits to keep statevector memory ≤ ' ...
                            '2¹⁴ × 16 B = 256 KB. Save writes a temp QASM and POSTs ' ...
                            '/api/circuits/upload/file (no new backend endpoint needed).']);

                case 'Notes'
                    s = struct( ...
                        'purpose', 'Free-form per-project working notes and operator memos.', ...
                        'doesText', [ ...
                            '• Persists markdown-ish text against the active project.' newline ...
                            '• No structured fields — pure freeform scratchpad.'], ...
                        'measurements', '— Not applicable.', ...
                        'formulas', '— Not applicable.', ...
                        'notes', [ ...
                            'Hidden from the sidebar by default — re-enable by adding ' ...
                            '''Notes'' back to navNames in NavigationManager. The NotesScreen / ' ...
                            'NotesViewModel are still wired so any cross-screen routing call ' ...
                            'continues to work.']);

                case 'Upload'
                    s = struct( ...
                        'purpose', ['File-import path for circuits authored outside the ' ...
                                    'Composer (.qasm).'], ...
                        'doesText', [ ...
                            '• Accepts .qasm files via file picker.' newline ...
                            '• Validates the source server-side.' newline ...
                            '• Renders a small preview before commit.'], ...
                        'measurements', [ ...
                            '• Qubit count, depth, gate-count vector (after server parse).'], ...
                        'formulas', '— Not applicable.', ...
                        'notes', [ ...
                            'Hidden from the sidebar — superseded by the Composer / Upload ' ...
                            'buttons on the Circuits toolbar. The screen + VM are still ' ...
                            'instantiated so cross-screen onSelectSection(''Upload'') calls ' ...
                            'continue to route correctly.']);

                case 'Analysis'
                    s = struct( ...
                        'purpose', ['Static-feature extraction, QTAUBench similarity, and the ' ...
                                    'Quantum Monte Carlo entry-point for the active circuit.'], ...
                        'doesText', [ ...
                            '• Extracts structural features from the QASM (qubit count, depth,' newline ...
                            '  gate composition, entanglement proxy).' newline ...
                            '• Runs nearest-neighbour similarity against the 250+ circuit QTAUBench corpus.' newline ...
                            '• Hosts the QMC popup for async amplitude estimation against IBM Runtime' newline ...
                            '  with optional Zero-Noise Extrapolation, dynamic decoupling, twirling, and TEM.' newline ...
                            '• Generates a vector-chart PDF report on completion.' newline ...
                            '• Each QMC run is a registered background task — close the popup or hit' newline ...
                            '  Run-in-background and the poll continues; the toast announces completion.'], ...
                        'measurements', [ ...
                            '• Qubit count, depth, gate count per type, entanglement score.' newline ...
                            '• QTAUBench similarity rank (top-K with similarity %).' newline ...
                            '• QMC amplitude estimate â, ε-precision, quadratic-speedup factor.' newline ...
                            '• Greeks (Δ / Γ / Vega / Θ / ρ), VaR, CVaR, ZNE-extrapolated value.'], ...
                        'formulas', [ ...
                            '• QAE estimate: â = Pr(|good⟩); classical MC shots N_MC = O(1/ε²);' newline ...
                            '  QAE shots N_QAE = O(1/ε) ⇒ speedup ~1/ε.' newline ...
                            '• ZNE extrapolation: fit E(λ_i) over scaled noise factors' newline ...
                            '  λ_i ∈ {1, 1.5, 2, 3} and extrapolate to λ → 0 (linear or Richardson).' newline ...
                            '• Greeks via finite-difference: Δ = ∂V/∂S, Γ = ∂²V/∂S², etc.'], ...
                        'notes', [ ...
                            'QMC submit returns a job_id immediately; the screen polls /api/qae/jobs/' ...
                            '{id} every 3 s. The IBM execution log is downloadable as JSONL matching ' ...
                            'the hybrid-QMC notebook schema (subcircuit_id, backend, shots, status, job_id, ' ...
                            'counts, error).']);

                case 'Detailed Analysis'
                    s = struct( ...
                        'purpose', ['Per-qubit drift, heatmaps, and cross-run comparisons over ' ...
                                    'completed jobs of the active circuit.'], ...
                        'doesText', [ ...
                            '• Compare axis — multi-run overlay of measured distributions.' newline ...
                            '• Heatmap axis — counts by basis state × run (drift in seconds / minutes).' newline ...
                            '• Temporal axis — per-bitstring count drift over time.' newline ...
                            '• Qubit axis — per-qubit metric across runs.' newline ...
                            '• RB Decay axis — randomized-benchmarking fidelity curve.' newline ...
                            '• Toolbar circuit selector + Analyze bridge back to the Analysis screen.'], ...
                        'measurements', [ ...
                            '• Bitstring frequency per run (top-K basis states).' newline ...
                            '• Per-qubit Z expectation ⟨Z_i⟩.' newline ...
                            '• Randomized-benchmarking fidelity decay constant α.'], ...
                        'formulas', [ ...
                            '• RB fidelity: F(m) = A · αᵐ + B, where m is the sequence length.' newline ...
                            '• Average gate error: r = (1 − α) · (d − 1) / d for d = 2 (single qubit).' newline ...
                            '• ⟨Z⟩: ⟨Z_i⟩ = (N_0 − N_1) / (N_0 + N_1) measured on qubit i.'], ...
                        'notes', [ ...
                            'All five axes are lazy-painted on first focus (commit 85197fe). The ' ...
                            'pre-perf-pass eager render added ~3 s to every screen entry.']);

                case 'Backends'
                    s = struct( ...
                        'purpose', ['Browse the live IBM Quantum fleet and pick primary / backup ' ...
                                    'backends for the active project.'], ...
                        'doesText', [ ...
                            '• Paginated list with qubit count, simulator flag, T1/T2 medians,' newline ...
                            '  gate-error medians, status.' newline ...
                            '• Right-panel Telemetry tab strip:' newline ...
                            '  — Overview — KPI + status summary.' newline ...
                            '  — Per-Qubit — color-coded heat grid (T1, T2, gate_err, readout_err, 2Q_err).' newline ...
                            '  — History — 7-day sparklines for T1, T2, 2Q error.' newline ...
                            '  — Topology — force-directed coupling-map graph with health-scored node colors.' newline ...
                            '• Primary / Backup selection persists to the project document.'], ...
                        'measurements', [ ...
                            '• T1 — relaxation time (μs, larger is better).' newline ...
                            '• T2 — coherence time (μs, larger is better).' newline ...
                            '• Single-qubit gate error (fraction; lower is better).' newline ...
                            '• Readout error (fraction; lower is better).' newline ...
                            '• 2Q gate error (echoed cross-resonance; lower is better).' newline ...
                            '• Queue position estimate.'], ...
                        'formulas', [ ...
                            '• Composite per-qubit health score (used for topology node color):' newline ...
                            '  score = w_T1·norm(T1) + w_T2·norm(T2) + w_gate·(1 − err_gate),' newline ...
                            '  with w_T1 = w_T2 = 0.3, w_gate = 0.4 (operator heuristic, not vendor-published).' newline ...
                            '• Quality bands (Backends Per-Qubit heat grid):' newline ...
                            '  T1 ≥ 100 μs → green; 50–100 μs → amber; <50 μs → red. T2 similar.' newline ...
                            '  err ≤ 0.5 % → green; 0.5–1 % → amber; >1 % → red.'], ...
                        'notes', [ ...
                            'Every successful /api/backends/{name}/calibration response is ' ...
                            'written through to the calibration_history Mongo collection (1 row ' ...
                            'per qubit per fetch); the History sparklines read from there with a ' ...
                            '7-day default lookback (TTL evicts > 7 d).']);

                case 'Benchmark'
                    s = struct( ...
                        'purpose', ['Configure execution parameters and mitigation strategy for ' ...
                                    'the active circuit on the picked backend.'], ...
                        'doesText', [ ...
                            '• Shot count (with bounds aware of cost cap).' newline ...
                            '• Mitigation level — None / Minimal / Standard / Aggressive / Custom.' newline ...
                            '• Schedule, max wall-clock, $ cost cap.' newline ...
                            '• Pushes the committed config into Benchmark Dashboard.'], ...
                        'measurements', [ ...
                            '• Shot count and effective shots after mitigation multiplier.' newline ...
                            '• Mitigation cost factor.' newline ...
                            '• Expected runtime (queue + execution).' newline ...
                            '• IQP cost where applicable.'], ...
                        'formulas', [ ...
                            '• Effective shots: N_eff = N_shots × c_mit, where c_mit ∈ [1, 10]' newline ...
                            '  scales with the level (None = 1, Aggressive ≈ 8–10).' newline ...
                            '• Cost: cost = N_eff × $_per_shot(backend).'], ...
                        'notes', [ ...
                            'Strategy comparison side-by-side lives on the Mitigation Compare ' ...
                            'screen; this screen commits the chosen one and hands it off.']);

                case 'Benchmark Dashboard'
                    s = struct( ...
                        'purpose', ['Cross-circuit / cross-strategy benchmark summary with ' ...
                                    'recommendations.'], ...
                        'doesText', [ ...
                            '• Aggregates committed Benchmark configs into a comparison grid.' newline ...
                            '• Surfaces recommendations: best fidelity / cheapest / best balance.' newline ...
                            '• Click a row to drill into the underlying Benchmark + Prediction.'], ...
                        'measurements', [ ...
                            '• Predicted fidelity, total shots, $ cost, expected runtime per row.'], ...
                        'formulas', [ ...
                            '• Pareto frontier on (cost, fidelity): a point is on the frontier' newline ...
                            '  iff no other point dominates it on both axes.'], ...
                        'notes', [ ...
                            'Powered by historical results — fresh configs land here after the ' ...
                            'Benchmark screen commits.']);

                case 'Circuit Cutting'
                    s = struct( ...
                        'purpose', ['Split a too-wide circuit into subcircuits that fit on ' ...
                                    'smaller backends, then reconstruct expectation values.'], ...
                        'doesText', [ ...
                            '• Three modes — Automatic (server picks cuts), Assisted (defaults' newline ...
                            '  pre-filled, user tweaks), Manual (user-driven cut locations + observables).' newline ...
                            '• Submits POST /cutting/batches and polls /cutting/batches/{id} every 3 s.' newline ...
                            '• Renders cut-plan KPI strip (k, sampling overhead, per-sub widths), per-subcircuit' newline ...
                            '  backend assignment cards, reconstructed expectation values.' newline ...
                            '• The whole submit + poll lifecycle is a registered background task — Run-in-background' newline ...
                            '  moves it to the header indicator and the toast announces completion.'], ...
                        'measurements', [ ...
                            '• Number of cuts k.' newline ...
                            '• Sampling overhead c² (and log₁₀ c²).' newline ...
                            '• Per-subcircuit qubit width.' newline ...
                            '• Reconstructed expectation value per Pauli string.'], ...
                        'formulas', [ ...
                            '• Quasiprobability decomposition: U = Σᵢ αᵢ · channel_i.' newline ...
                            '• Sampling overhead per cut: c² = (Σᵢ |αᵢ|)².' newline ...
                            '• Total shot inflation for additive error ε at confidence 1−δ:' newline ...
                            '  N_total ≥ N_target × c² · log(2/δ) / ε².' newline ...
                            '• Reconstruction: ⟨O⟩_full = Σ_assignments ∏ᵢ αᵢ(assignment_i) · ⟨O⟩_sub.'], ...
                        'notes', [ ...
                            'Submit timeout is 600 s (busy-day tolerant). The legacy 120-s ' ...
                            'AsyncRunner cap was bumped to keep IBM-busy submits from failing ' ...
                            'with AsyncRunner:Timeout.']);

                case 'Prediction'
                    s = struct( ...
                        'purpose', ['Pre-submit predicted fidelity for the active circuit on ' ...
                                    'the chosen backend.'], ...
                        'doesText', [ ...
                            '• Trains-once / serves-many model uses circuit features + backend calibration' newline ...
                            '  to estimate F̂.' newline ...
                            '• Renders distribution (mean ± σ).' newline ...
                            '• Error budget breakdown — 1Q errors / 2Q errors / readout / decoherence.' newline ...
                            '• Confidence band around the central estimate.'], ...
                        'measurements', [ ...
                            '• Predicted fidelity F̂ with uncertainty σ.' newline ...
                            '• Per-source error contribution (% of total error budget).'], ...
                        'formulas', [ ...
                            '• Layer fidelity (gate sources):' newline ...
                            '  F_layer = ∏(1 − err_1q)^{n_1q} · ∏(1 − err_2q)^{n_2q} · ∏(1 − err_ro)^{n_ro}.' newline ...
                            '• Decoherence factor:' newline ...
                            '  F_T = exp(−τ_layer · (1/T1 + 1/(2·T2))) for layer execution time τ_layer.' newline ...
                            '• Compound prediction:' newline ...
                            '  F̂ ≈ ∏_layers (F_layer · F_T).'], ...
                        'notes', [ ...
                            'Prediction is a rough operator-grade estimate intended for ' ...
                            '"pick a backend" decisions, not a transpiler simulator. The training ' ...
                            'corpus is project-internal historical jobs.']);

                case 'Mitigation Compare'
                    s = struct( ...
                        'purpose', ['Pre-submit side-by-side cost preview across mitigation ' ...
                                    'strategies — pick before paying for shots.'], ...
                        'doesText', [ ...
                            '• Multi-select backend strip + multi-select mitigation-level strip.' newline ...
                            '• Fires parallel POST /api/mitigation/estimate per (backend × level) cell.' newline ...
                            '• Renders Cost / Shot-multiplier / Runtime / IQP-cost cards.' newline ...
                            '• Color-graded shot-multiplier ranking bar chart.' newline ...
                            '• Recommendation strip: cheapest / best-balance / most-aggressive.'], ...
                        'measurements', [ ...
                            '• Shot multiplier per (backend, level).' newline ...
                            '• Cost ($) per cell.' newline ...
                            '• Expected runtime per cell.' newline ...
                            '• IQP cost (Imbalance-Quasiprobability coefficient).'], ...
                        'formulas', [ ...
                            '• Shot multiplier per level (empirical mapping):' newline ...
                            '  None = 1.0  ·  Minimal ≈ 1.5–2.0  ·  Standard ≈ 3–4  ·  Aggressive ≈ 8–10.' newline ...
                            '  Custom is user-driven via the JSON form on the Benchmark screen.' newline ...
                            '• Cost: cost = N_shots × multiplier × $_per_shot(backend).' newline ...
                            '• Expected runtime: t = (N_shots × multiplier × t_per_shot) + queue_position × t_queue_avg.'], ...
                        'notes', [ ...
                            'Phase A ships cost preview only. Phase B (live A/B with histograms ' ...
                            'via real job submissions) is a planned follow-up. Differentiator ' ...
                            'surface — no competitor (IBM / AWS / Azure / Google / Quantinuum / ' ...
                            'IonQ / Rigetti) ships a side-by-side cost comparator today.']);

                case 'Resource Estimator'
                    s = struct( ...
                        'purpose', ['Fault-tolerant overhead planner — physical qubits + runtime ' ...
                                    'to run a circuit under surface-code error correction.'], ...
                        'doesText', [ ...
                            '• Inputs: active circuit (uploaded or live Composer model) + FT parameters' newline ...
                            '  (physical error rate p_phys, target logical error rate p_L, surface-code cycle τ).' newline ...
                            '• Computes surface-code distance, physical-per-logical, T-state budget,' newline ...
                            '  T-factory count, total runtime.' newline ...
                            '• Renders Logical / Physical / Runtime result cards.' newline ...
                            '• Renders qubit-allocation pie (data / ancilla / T-factory).' newline ...
                            '• Scale-narration strip — "near-term" / "exceeds today''s largest devices" /' newline ...
                            '  "fault-tolerant scale".'], ...
                        'measurements', [ ...
                            '• Surface-code distance d.' newline ...
                            '• Physical qubits per logical qubit.' newline ...
                            '• T-state budget (count).' newline ...
                            '• T-factory footprint and count.' newline ...
                            '• Total runtime.'], ...
                        'formulas', [ ...
                            '• Distance (Fowler et al. inverse threshold):' newline ...
                            '  d ≥ ⌈1 / log₁₀(p_th / p_phys)⌉,  with p_th ≈ 1 %.' newline ...
                            '• Physical per logical:' newline ...
                            '  2·d² + 1.' newline ...
                            '• T-state budget (Solovay-Kitaev rough bound for arbitrary rotations):' newline ...
                            '  n_T = n_T_direct + 7·n_Toffoli + ⌈c·log₂(1/ε)⌉·n_Rotation.' newline ...
                            '• T-factory footprint (15-to-1 distillation):' newline ...
                            '  16·d²·(2·d² + 1) physical qubits per factory.' newline ...
                            '• Total runtime:' newline ...
                            '  T = circuit_depth × τ + T-factory busy time.'], ...
                        'notes', [ ...
                            'Closest analogue today is Azure Quantum''s Resource Estimator. The ' ...
                            'numbers are theoretical lower bounds — actual transpiler / hardware ' ...
                            'compilation overhead is not modeled.']);

                case 'Run Planner'
                    s = struct( ...
                        'purpose', ['Cost-aware run optimisation — "give me fidelity ≥ F at ' ...
                                    'minimum $ cost" in one click.'], ...
                        'doesText', [ ...
                            '• Inputs: circuit + target fidelity slider + shot count.' newline ...
                            '• Dispatches one PredictionService.predict (per-backend base fidelity) plus' newline ...
                            '  N parallel MitigationService.estimate (per-strategy cost).' newline ...
                            '• Cross-multiplies into M·N candidate configurations.' newline ...
                            '• Applies heuristic mitigation-fidelity factor (None ×1.00 → Aggressive ×1.30,' newline ...
                            '  capped at 0.99).' newline ...
                            '• Computes the Pareto frontier (cost ↗ fidelity ↗).' newline ...
                            '• Recommends the cheapest config that hits the target; falls back to highest-fidelity' newline ...
                            '  overall when no config meets it.' newline ...
                            '• Renders Pareto scatter (all points + frontier overlay + target line + optimal star)' newline ...
                            '  and a recommendation card with Submit-this-run / Bundle-this-config hand-offs.'], ...
                        'measurements', [ ...
                            '• Per-(backend, strategy) predicted fidelity and $ cost.' newline ...
                            '• Pareto rank.'], ...
                        'formulas', [ ...
                            '• Predicted fidelity (post-mitigation):' newline ...
                            '  F̂_ij = min(0.99, F̂_backend(i) × mit_factor(j)).' newline ...
                            '• Pareto-optimal definition:' newline ...
                            '  (c_i, F_i) is Pareto-optimal iff no (c_j, F_j) satisfies' newline ...
                            '  c_j ≤ c_i AND F_j ≥ F_i, with at least one strict.' newline ...
                            '• Optimal pick:' newline ...
                            '  argmin_i { c_i  :  F_i ≥ F_target  } from the Pareto frontier.'], ...
                        'notes', [ ...
                            'Tier-3 moat — unaddressed by all 7 platforms in the audit (IBM / ' ...
                            'AWS / Azure / Google / Quantinuum / IonQ / Rigetti). No competitor ' ...
                            'answers "give me fidelity F at minimum cost" in one click.']);

                case 'Jobs'
                    s = struct( ...
                        'purpose', 'Live job-monitoring dashboard for the active project.', ...
                        'doesText', [ ...
                            '• Six-column table — Job ID / Circuit / Backend / Status / Progress / Created.' newline ...
                            '• Auto-refresh every 5 s while the screen is visible.' newline ...
                            '• Detailed logs panel for the selected job.' newline ...
                            '• Sort newest-first by submitted_at (server-side, with client defensive re-sort).'], ...
                        'measurements', [ ...
                            '• Job state — Queued / Running / Completed / Failed / Cancelled.' newline ...
                            '• Progress % (server-reported).' newline ...
                            '• IBM job_id (Runtime).' newline ...
                            '• submitted_at timestamp.'], ...
                        'formulas', '— Not applicable. Pure orchestration.', ...
                        'notes', [ ...
                            'Self-healing list: up to 10 in-flight jobs per /api/jobs call are ' ...
                            'lazy-refreshed from IBM Quantum so progress advances even when the ' ...
                            'Celery beat sweeper is not deployed.']);

                case 'Results'
                    s = struct( ...
                        'purpose', ['Measured vs predicted vs ideal counts side-by-side for the ' ...
                                    'first completed job in the active project.'], ...
                        'doesText', [ ...
                            '• Auto-picks the first completed job in the active project.' newline ...
                            '• Side-by-side bar chart over the top-K basis states (Measured / Predicted / Ideal).' newline ...
                            '• Shot count, fidelity delta, top-state probability table.'], ...
                        'measurements', [ ...
                            '• Per-basis-state counts (measured, from /api/jobs/{id}/result).' newline ...
                            '• Predicted distribution from the Prediction model.' newline ...
                            '• Ideal counts from the local statevector (when the circuit fits ≤ 14 qubits).'], ...
                        'formulas', [ ...
                            '• Total-variation distance:' newline ...
                            '  TVD = ½ · Σᵢ |p_i^measured − p_i^ideal|.' newline ...
                            '• Empirical fidelity (Hellinger / Bhattacharyya overlap):' newline ...
                            '  F̂ = ( Σᵢ √(p_i^measured · p_i^ideal) )².'], ...
                        'notes', [ ...
                            'Ideal counts only render when the circuit fits the local statevector ' ...
                            'limit (≤ 14 qubits). Above that, the chart shows Measured / Predicted only.']);

                case 'Reports'
                    s = struct( ...
                        'purpose', ['PDF report generation and viewing for shareable analysis ' ...
                                    'bundles.'], ...
                        'doesText', [ ...
                            '• Generates a vector-chart PDF for the chosen run — embeds circuit diagram,' newline ...
                            '  KPI strip, prediction, mitigation cost, results comparison, error budget.' newline ...
                            '• Lists prior reports with download / share links.' newline ...
                            '• QMC reports get a dedicated builder with loss distribution + VaR + CDF +' newline ...
                            '  QAE-vs-classical-MC convergence + amplitude bar + ZNE curve + Greeks table +' newline ...
                            '  market scenario + benchmark matches.'], ...
                        'measurements', [ ...
                            '• Report metadata — id, created_at, run_id, backend, status.'], ...
                        'formulas', '— Not applicable.', ...
                        'notes', [ ...
                            'POST /api/reports/generate returns a report_id; GET /api/reports/{id}/download ' ...
                            'streams the PDF. The QMC PDF builder uses native ReportLab vector charts ' ...
                            '(crisp at any zoom level).']);

                case 'Settings'
                    s = struct( ...
                        'purpose', ['Account preferences, defaults, storage, and notification ' ...
                                    'configuration.'], ...
                        'doesText', [ ...
                            '• Profile — display name, organization, avatar key.' newline ...
                            '• Defaults — default project, default backend, default shot count.' newline ...
                            '• Theme — Light / Dark / Dracula / Solarized / Nord / Monokai / ...' newline ...
                            '• IBM Runtime token verification.' newline ...
                            '• Notification email + verbosity (digest cadence, severity filter).' newline ...
                            '• Local cache controls.'], ...
                        'measurements', '— Not applicable.', ...
                        'formulas', '— Not applicable.', ...
                        'notes', [ ...
                            'IBM token is verified server-side via GET /api/settings/ibm-config; it ' ...
                            'is never echoed back to the client. Theme changes are persisted to local ' ...
                            'storage and re-applied on next launch (no flash-of-light-theme).']);

                case 'QEC Simulation'
                    s = struct( ...
                        'purpose', ['Simulate a logical qubit under a configurable noise model — ' ...
                                    'gauge how a surface-code patch holds up.'], ...
                        'doesText', [ ...
                            '• Pick a code (currently surface code, distance d).' newline ...
                            '• Pick a noise model — depolarizing / phase damping / amplitude damping /' newline ...
                            '  measurement error / circuit-level composite.' newline ...
                            '• Pick shot count and cycle count.' newline ...
                            '• Runs N rounds of syndrome extraction + decoder.' newline ...
                            '• Reports the logical-error rate p_L.'], ...
                        'measurements', [ ...
                            '• Logical-error rate p_L per cycle.' newline ...
                            '• Physical-error rate per round (input).' newline ...
                            '• Syndrome-extraction success rate.'], ...
                        'formulas', [ ...
                            '• Surface-code threshold (Fowler et al.):' newline ...
                            '  p_th ≈ 1.0 % for code-capacity noise,' newline ...
                            '  p_th ≈ 0.7 % for phenomenological,' newline ...
                            '  p_th ≈ 0.5–0.7 % for circuit-level.' newline ...
                            '• Subthreshold scaling:' newline ...
                            '  p_L ∝ (p_phys / p_th)^⌈(d+1)/2⌉  — each distance bump roughly halves' newline ...
                            '  the logical exponent.'], ...
                        'notes', [ ...
                            'Decoder is currently MWPM (minimum-weight perfect matching) on the ' ...
                            'syndrome graph. Heavier decoders (Union-Find, BP+OSD) are a planned ' ...
                            'follow-up.']);

                case 'QEC Visualization'
                    s = struct( ...
                        'purpose', ['3D Bloch sphere, surface-code lattice rendering, and ' ...
                                    'error-propagation animation.'], ...
                        'doesText', [ ...
                            '• Bloch axis — animates |ψ⟩ evolution under Pauli noise.' newline ...
                            '• Lattice axis — colors data / measurement / ancilla qubits;' newline ...
                            '  highlights syndromes; lights up error chains in red.' newline ...
                            '• Decay axis — plots Z fidelity vs cycle count.' newline ...
                            '• ErrorWeight axis — distribution of error chains by Hamming weight.'], ...
                        'measurements', [ ...
                            '• Bloch vector (⟨X⟩, ⟨Y⟩, ⟨Z⟩) with |r| ≤ 1.' newline ...
                            '• Lattice node positions and per-node state.' newline ...
                            '• Error-chain Hamming-weight histogram.'], ...
                        'formulas', [ ...
                            '• Density matrix on Bloch sphere:' newline ...
                            '  ρ = ½(I + ⟨X⟩·X + ⟨Y⟩·Y + ⟨Z⟩·Z).' newline ...
                            '• Z-fidelity decay (effective single-qubit picture):' newline ...
                            '  F_Z(n) = ½(1 + cos(θ_n)) · exp(−n / τ_Z) for n cycles.'], ...
                        'notes', [ ...
                            'All four axes are lazy-painted on first focus (commit 6564a50). The ' ...
                            'lattice highlighter uses a force-directed layout for non-grid codes.']);

                otherwise
                    s = struct( ...
                        'purpose', 'No help content registered for this screen yet.', ...
                        'doesText', ['Add an entry in src/presentation/app/HelpContent.m ' ...
                                     'using the existing case arms as templates.'], ...
                        'measurements', '—', ...
                        'formulas', '—', ...
                        'notes', '');
            end
        end

        function s = appBody()
            % appBody  End-user-oriented help struct for the application
            %   as a whole. Reuses the 5-field schema so renderHtml can
            %   stay unchanged; appLabels() overrides the section header
            %   text so each section reads in app-level language
            %   ("Key features", "Recommended workflow", ...) instead of
            %   the per-screen wording.
            s = struct( ...
                'purpose', [ ...
                    'A unified desktop workspace for designing, ' ...
                    'predicting, planning, running, and analyzing ' ...
                    'quantum-circuit experiments on IBM Quantum and ' ...
                    'simulator backends — without juggling notebooks, ' ...
                    'vendor SDKs, or terminal scripts.'], ...
                'doesText', [ ...
                    '• Visual circuit composer with click-to-place gates and a' newline ...
                    '  bidirectional OpenQASM 2.0 mirror, plus 12 ready-made templates' newline ...
                    '  (Bell, GHZ, QFT, Grover, Bernstein–Vazirani, Deutsch–Jozsa,' newline ...
                    '  Phase Estimation, VQE H₂, QAOA, Trotter, Teleportation, Superdense).' newline ...
                    '• IBM Quantum fleet browser with live telemetry — T1, T2,' newline ...
                    '  gate errors, readout error, 7-day calibration history, force-' newline ...
                    '  directed topology graph.' newline ...
                    '• Pre-submit fidelity prediction combining circuit features with' newline ...
                    '  backend calibration.' newline ...
                    '• Cost-aware Run Planner — "give me fidelity F at minimum $ cost"' newline ...
                    '  in one click.' newline ...
                    '• Error-mitigation strategy comparator — side-by-side cost,' newline ...
                    '  shot-multiplier, and runtime for None / Minimal / Standard /' newline ...
                    '  Aggressive / Custom levels.' newline ...
                    '• Fault-tolerant Resource Estimator — surface-code distance,' newline ...
                    '  physical qubits, T-state budget, total runtime.' newline ...
                    '• Circuit cutting + reconstruction for circuits wider than the' newline ...
                    '  chosen backend.' newline ...
                    '• Quantum Monte Carlo workflow with Zero-Noise Extrapolation,' newline ...
                    '  dynamical decoupling, Pauli twirling.' newline ...
                    '• Live job monitoring with auto-refresh, detailed logs, and a' newline ...
                    '  self-healing in-flight refresh.' newline ...
                    '• Vector-chart PDF reports and one-click reproducibility' newline ...
                    '  bundles (ZIP with circuit, calibration snapshot, mitigation' newline ...
                    '  estimates, FT estimate, manifest with SHA-256 checksums).' newline ...
                    '• QEC simulation and 3D visualization (Bloch, surface-code' newline ...
                    '  lattice, error chains).' newline ...
                    '• Background-task system — long IBM jobs run while you keep' newline ...
                    '  working; the header indicator shows what is running and a' newline ...
                    '  toast announces each completion.'], ...
                'measurements', [ ...
                    '• Pick or create a project on Projects.' newline ...
                    '• Author a circuit on Composer, or import one on Circuits.' newline ...
                    '• Pick primary + backup backends on Backends.' newline ...
                    '• Predict fidelity on Prediction.' newline ...
                    '• Compare mitigation strategies on Mitigation Compare — do this' newline ...
                    '  before paying for shots, Aggressive can be 8–10× the cost.' newline ...
                    '• Plan the run on Run Planner — choose the cheapest configuration' newline ...
                    '  that hits your target fidelity.' newline ...
                    '• Optional: estimate fault-tolerant overhead on Resource Estimator.' newline ...
                    '• Optional: cut a wide circuit on Circuit Cutting.' newline ...
                    '• Configure shots + mitigation on Benchmark and submit.' newline ...
                    '• Watch progress on Jobs — auto-refreshes every 5 seconds.' newline ...
                    '• Analyze on Results and Detailed Analysis.' newline ...
                    '• Share via PDF on Reports, or a reproducibility bundle from Composer.'], ...
                'formulas', [ ...
                    '• Amplitude estimation (Brassard · Høyer · Mosca · Tapp) for' newline ...
                    '  Quantum Monte Carlo — quadratic speedup over classical Monte Carlo.' newline ...
                    '• Zero-noise extrapolation (Temme · Bravyi · Gambetta) for' newline ...
                    '  error mitigation.' newline ...
                    '• Dynamical decoupling and Pauli twirling for coherence preservation' newline ...
                    '  and noise tailoring.' newline ...
                    '• Quasi-probability circuit cutting (Bravyi · Smith · Smolin)' newline ...
                    '  with quasi-probability reconstruction for wide circuits.' newline ...
                    '• Surface-code resource estimation (Fowler · Mariantoni · Martinis' newline ...
                    '  · Cleland) — distance, physical-per-logical, T-factory footprint.' newline ...
                    '• Solovay-Kitaev decomposition for T-state budgeting under arbitrary' newline ...
                    '  single-qubit rotations.' newline ...
                    '• Pareto-frontier optimization for cost-aware run planning.' newline ...
                    '• Minimum-weight perfect matching (MWPM) decoder for QEC' newline ...
                    '  simulation under surface-code error correction.' newline ...
                    '• Hellinger / Bhattacharyya empirical fidelity for measured vs' newline ...
                    '  predicted vs ideal comparison on Results.'], ...
                'notes', [ ...
                    '• Every screen has a "?" icon next to its title — click it for' newline ...
                    '  per-screen help including the formulas the screen computes.' newline ...
                    '• Long-running tasks (Run QMC, Circuit Cutting) can run in the' newline ...
                    '  background — hit "Run in background" on the loading overlay or' newline ...
                    '  navigate away; the header indicator shows running tasks and a' newline ...
                    '  toast announces completion. Click "View" on the toast to jump' newline ...
                    '  back to the result.' newline ...
                    '• Themes switch from Settings — Light, Dark, Dracula, Solarized,' newline ...
                    '  Nord, Monokai, and others.' newline ...
                    '• Projects let you isolate work — switch via the project dropdown' newline ...
                    '  in the toolbar.' newline ...
                    '• Use the Composer''s local statevector simulator (≤ 14 qubits) to' newline ...
                    '  sanity-check before paying for shots.' newline ...
                    '• The Reproducibility Bundle (Composer → 📦) is the canonical way' newline ...
                    '  to share or archive a run — ZIP with SHA-256 checksums covering' newline ...
                    '  the circuit, calibration, mitigation, and resource estimate.']);
        end

        function s = appLabels()
            % appLabels  Per-section header overrides for the app-level
            %   help dialog. Field names match HelpContent body fields.
            s = struct( ...
                'doesText',     'Key features', ...
                'measurements', 'Recommended workflow', ...
                'formulas',     'Algorithms in use', ...
                'notes',        'Tips & references');
        end

        function html = renderHtml(displayName, body, labels)
            % renderHtml  Wrap the help struct into a styled HTML page for
            %   the uihtml component inside the help dialog. Pulls colors
            %   from Theme so dark / Dracula / Solarized variants render
            %   coherently.
            %
            %   Optional `labels` struct overrides the section headers
            %   (so the app-level dialog can read "Key features /
            %   Recommended workflow / Algorithms in use / Tips" instead
            %   of the screen-level "What it does / Measurements /
            %   Formulas / Notes"). Existing screen-level callers omit
            %   the arg and get the original labels.
            if nargin < 3; labels = struct(); end
            try
                bg       = HelpContent.toHex(Theme.COLOR_CARD);
                fg       = HelpContent.toHex(Theme.COLOR_HEADING);
                muted    = HelpContent.toHex(Theme.COLOR_MUTED);
                divider  = HelpContent.toHex(Theme.COLOR_DIVIDER);
                accent   = HelpContent.toHex(Theme.OVERLAY_ACCENT);
                codeBg   = HelpContent.toHex(Theme.COLOR_ACCENT_BG);
            catch
                bg = '#262B33'; fg = '#F2F4F7'; muted = '#A0A6B0';
                divider = '#3B4252'; accent = '#735BCB'; codeBg = '#2D3340';
            end

            esc = @(s) HelpContent.htmlEscape(s);
            sec = @(title, raw) sprintf( ...
                ['<section class="sec">' ...
                 '<div class="sec-head"><span class="sec-bar"></span>' ...
                 '<h3 class="sec-title">%s</h3></div>' ...
                 '<div class="sec-body">%s</div></section>'], ...
                esc(title), HelpContent.bodyBlock(raw, codeBg));

            html = sprintf([ ...
                '<!DOCTYPE html><html><head><meta charset="utf-8"><style>' ...
                'html,body{margin:0;padding:0;background:%s;color:%s;' ...
                'font-family:-apple-system,"Segoe UI",Helvetica,Arial,sans-serif;' ...
                'font-size:14px;line-height:1.6;' ...
                '-webkit-font-smoothing:antialiased;}' ...
                '.wrap{padding:28px 34px 34px 34px;max-width:680px;}' ...
                '.title{color:%s;font-size:22px;font-weight:700;' ...
                'margin:0 0 6px 0;letter-spacing:-0.01em;line-height:1.25;}' ...
                '.lede{color:%s;font-size:14px;margin:0;line-height:1.55;}' ...
                '.hr{height:1px;background:%s;border:none;margin:20px 0 0 0;' ...
                'opacity:0.55;}' ...
                '.sec{margin-top:24px;}' ...
                '.sec-head{display:flex;align-items:center;margin:0 0 10px 0;}' ...
                '.sec-bar{display:inline-block;width:3px;height:13px;' ...
                'background:%s;border-radius:2px;margin-right:9px;}' ...
                '.sec-title{color:%s;font-size:11px;font-weight:700;' ...
                'letter-spacing:0.12em;text-transform:uppercase;margin:0;}' ...
                '.sec-body{color:%s;font-size:13.5px;line-height:1.6;}' ...
                '.sec-body p{margin:6px 0;}' ...
                '.sec-body ul{margin:4px 0 4px 0;padding:0;list-style:none;}' ...
                '.sec-body li{position:relative;padding-left:18px;margin:5px 0;}' ...
                '.sec-body li::before{content:"";position:absolute;left:4px;' ...
                'top:9px;width:5px;height:5px;border-radius:50%%;' ...
                'background:%s;opacity:0.75;}' ...
                '.sec-body .formula-list{list-style:none;padding-left:0;}' ...
                '.sec-body .formula-list li{padding-left:0;}' ...
                '.sec-body .formula-list li::before{display:none;}' ...
                '.formula{background:%s;border:1px solid %s;border-radius:7px;' ...
                'padding:9px 13px;font-family:"SF Mono","Consolas","Menlo",' ...
                '"Roboto Mono",monospace;font-size:12.5px;color:%s;' ...
                'margin:6px 0;white-space:pre-wrap;display:block;}' ...
                '.empty{color:%s;font-style:italic;font-size:13px;margin:0;}' ...
                '</style></head><body><div class="wrap">' ...
                '<h1 class="title">%s</h1>' ...
                '<p class="lede">%s</p>' ...
                '<hr class="hr"/>' ...
                '%s%s%s%s' ...
                '</div></body></html>'], ...
                bg, fg, fg, muted, divider, accent, accent, fg, muted, ...
                codeBg, divider, fg, muted, ...
                esc(char(displayName)), esc(char(body.purpose)), ...
                sec(HelpContent.getLabel(labels, 'doesText',     'What it does'),  body.doesText), ...
                sec(HelpContent.getLabel(labels, 'measurements', 'Measurements'),  body.measurements), ...
                sec(HelpContent.getLabel(labels, 'formulas',     'Formulas'),      body.formulas), ...
                sec(HelpContent.getLabel(labels, 'notes',        'Notes'),         body.notes));
        end

    end

    methods (Static, Access = private)

        function html = bodyBlock(raw, codeBg) %#ok<INUSD>
            % bodyBlock  Convert a multi-line text block into HTML. Lines
            %   beginning with "•" or "-" become list items; everything
            %   else becomes paragraph text. Indented continuations are
            %   folded onto the previous list item.
            %
            %   Empty-state convention: a single line that starts with an
            %   em-dash ("— Not applicable." etc.) is rendered as a muted
            %   italic note instead of a paragraph — cleaner than the
            %   raw em-dash + sentence on a regular line.
            %
            %   Formula blocks (bullet lines containing one of "=", "∝",
            %   "≈", "≥", "≤", or a leading variable-name colon like
            %   "Distance:") drop the bullet dot and render each item as
            %   a rounded monospace card.
            txt = char(raw);
            if isempty(strtrim(txt)); html = ''; return; end
            esc = @(s) HelpContent.htmlEscape(s);

            % Empty-state shortcut: single-line em-dash note.
            trimmed = strtrim(txt);
            if ~contains(trimmed, newline) && (startsWith(trimmed, char(8212)) ...
                    || startsWith(trimmed, char(8211)) || startsWith(trimmed, '-'))
                stripped = strtrim(regexprep(trimmed, '^[—–\-]\s*', ''));
                html = sprintf('<p class="empty">%s</p>', esc(stripped));
                return;
            end

            lines = regexp(txt, '\r?\n', 'split');

            % Detect whether this block is a formula block by scanning
            % bullet lines for math glyphs.
            isFormulaBlock = false;
            for i = 1:numel(lines)
                t = strtrim(lines{i});
                if (startsWith(t, '•') || startsWith(t, '-')) && ...
                        (contains(t, '=') || contains(t, '∝') ...
                        || contains(t, '≈') || contains(t, '≥') || contains(t, '≤'))
                    isFormulaBlock = true; break;
                end
            end

            html = '';
            inList = false;
            buf = '';
            ulOpen = '';
            for i = 1:numel(lines)
                raw_i = lines{i};
                t = strtrim(raw_i);
                if startsWith(t, '•') || startsWith(t, '-')
                    if ~isempty(strtrim(buf))
                        html = [html '<p>' esc(buf) '</p>']; buf = ''; %#ok<AGROW>
                    end
                    if ~inList
                        if isFormulaBlock
                            ulOpen = '<ul class="formula-list">';
                        else
                            ulOpen = '<ul>';
                        end
                        html = [html ulOpen]; inList = true; %#ok<AGROW>
                    end
                    item = strtrim(t(2:end));
                    if isFormulaBlock
                        html = [html sprintf('<li><div class="formula">%s</div></li>', esc(item))]; %#ok<AGROW>
                    else
                        html = [html sprintf('<li>%s</li>', esc(item))]; %#ok<AGROW>
                    end
                elseif startsWith(raw_i, ' ') && inList && ~isempty(t)
                    % Indented continuation of the previous list item.
                    if isFormulaBlock
                        % Continue inside the most recent .formula div by
                        % stripping its trailing close + re-opening.
                        html = regexprep(html, '</div></li>$', '');
                        html = [html sprintf('<br/>%s</div></li>', esc(t))]; %#ok<AGROW>
                    else
                        html = regexprep(html, '</li>$', '');
                        html = [html ' ' esc(t) '</li>']; %#ok<AGROW>
                    end
                else
                    if inList
                        html = [html '</ul>']; inList = false; %#ok<AGROW>
                    end
                    if isempty(t)
                        if ~isempty(strtrim(buf))
                            html = [html '<p>' esc(buf) '</p>']; buf = ''; %#ok<AGROW>
                        end
                    else
                        if isempty(buf); buf = t; else; buf = [buf ' ' t]; end %#ok<AGROW>
                    end
                end
            end
            if inList; html = [html '</ul>']; end
            if ~isempty(strtrim(buf)); html = [html '<p>' esc(buf) '</p>']; end
        end

        function s = htmlEscape(s)
            if isempty(s); s = ''; return; end
            s = char(s);
            s = strrep(s, '&', '&amp;');
            s = strrep(s, '<', '&lt;');
            s = strrep(s, '>', '&gt;');
        end

        function lbl = getLabel(labels, field, defaultLbl)
            % getLabel  Pull labels.<field> if present + non-empty; fall
            %   back to defaultLbl otherwise. Used by renderHtml to let
            %   the app-level dialog override per-section header text
            %   without breaking the 22 existing screen-level callers
            %   that pass no labels at all.
            if isstruct(labels) && isfield(labels, field) ...
                    && ~isempty(labels.(field))
                lbl = char(labels.(field));
            else
                lbl = defaultLbl;
            end
        end

        function h = toHex(rgb)
            % toHex  RGB triple in [0..1] → #RRGGBB string.
            try
                r = max(0, min(255, round(rgb(1) * 255)));
                g = max(0, min(255, round(rgb(2) * 255)));
                b = max(0, min(255, round(rgb(3) * 255)));
                h = sprintf('#%02X%02X%02X', r, g, b);
            catch
                h = '#262B33';
            end
        end

    end
end
