% seed_reports.m ───────────────────────────────────────────────────────────────
% Generates reports for projects and standalone via the REST API.
%
% Usage:
%   >> run('scripts/seed_reports.m')
%
% Provides data for: Reports screen (report list, download, preview)
% Prerequisites: seed_projects.m (projects must exist)
% ──────────────────────────────────────────────────────────────────────────────

fprintf('\n=== QTAU Seed: Generating reports ===\n\n');

% ── Configuration ────────────────────────────────────────────────────────────
BASE_URL   = 'http://34.42.87.190:5715';
LOGIN_PATH = '/api/auth/login';
USERNAME   = 'admin';
PASSWORD   = 'passw0rd';

% ── Step 1: Authenticate ────────────────────────────────────────────────────
fprintf('[1/3] Logging in as "%s" ... ', USERNAME);
try
    import matlab.net.http.*
    import matlab.net.http.field.*
    import matlab.net.http.io.*
    body = FormProvider('username', USERNAME, 'password', PASSWORD);
    req  = RequestMessage('POST', ...
        [ContentTypeField(MediaType('application/x-www-form-urlencoded'))], body);
    resp = req.send(matlab.net.URI([BASE_URL LOGIN_PATH]));
    if resp.StatusCode ~= 200
        error('Login failed with status %d', int32(resp.StatusCode));
    end
    token = string(resp.Body.Data.access_token);
    fprintf('OK\n');
catch ME
    fprintf('FAILED\n  %s\n', ME.message);
    return;
end

authHeader = {'Authorization', char("Bearer " + token)};
getOpts  = weboptions('Timeout', 30, 'ContentType', 'json', 'HeaderFields', authHeader);
postOpts = weboptions('Timeout', 60, 'MediaType', 'application/json', ...
    'ContentType', 'json', 'HeaderFields', authHeader);

% ── Step 2: Fetch projects and jobs ──────────────────────────────────────────
fprintf('[2/3] Fetching projects and jobs ... ');
try
    projResp = webread([BASE_URL '/api/projects'], getOpts);
    projects = projResp.projects;
    nProj    = numel(projects);
catch ME
    fprintf('FAILED (%s)\n', ME.message); return;
end

jobIds = {};
try
    jobResp = webread([BASE_URL '/api/jobs'], getOpts);
    if isstruct(jobResp) && isfield(jobResp, 'jobs')
        jobs = jobResp.jobs;
        for j = 1:numel(jobs)
            jobIds{end+1} = string(jobs(j).job_record_id); %#ok<SAGROW>
        end
    end
catch
    % Jobs are optional for reports
end
fprintf('found %d projects, %d jobs\n', nProj, numel(jobIds));

% ── Step 3: Generate reports ─────────────────────────────────────────────────
fprintf('[3/3] Generating reports ...\n');

% 3a. Project-scoped reports
projectReportTemplates = { ...
    struct('title', 'Circuit Analysis Summary',         'format', 'pdf',  'report_type', 'technical', ...
           'sections', {{'summary', 'features'}},       'audience', 'Research Team', ...
           'notes', 'Automated circuit feature extraction and benchmark matching results.'); ...
    struct('title', 'Backend Selection Rationale',      'format', 'pdf',  'report_type', 'technical', ...
           'sections', {{'summary', 'comparison'}},     'audience', 'Hardware Team', ...
           'notes', 'Comparison of candidate backends with predicted fidelity rankings.'); ...
    struct('title', 'Benchmark Configuration Report',   'format', 'html', 'report_type', 'technical', ...
           'sections', {{'summary', 'features', 'comparison'}}, 'audience', 'Engineering Team', ...
           'notes', 'Transpilation strategy comparison and benchmark parameter selection.'); ...
    struct('title', 'Prediction & Risk Assessment',     'format', 'pdf',  'report_type', 'technical', ...
           'sections', {{'summary', 'prediction'}},     'audience', 'Research Team', ...
           'notes', 'Fidelity prediction with error budget breakdown and confidence intervals.'); ...
    struct('title', 'Executive Project Summary',        'format', 'pdf',  'report_type', 'executive', ...
           'sections', {{'summary'}},                   'audience', 'Lab Director', ...
           'notes', 'High-level project status and key findings for management review.'); ...
};

projectReportCount = 0;
nProjReports = min(nProj, numel(projectReportTemplates));

for i = 1:nProjReports
    proj = projects(i);
    pid  = string(proj.project_id);
    name = string(proj.name);
    tmpl = projectReportTemplates{i};

    payload = struct( ...
        'title',       sprintf('%s — %s', tmpl.title, char(name)), ...
        'report_type', tmpl.report_type, ...
        'format',      tmpl.format, ...
        'sections',    {tmpl.sections}, ...
        'audience',    tmpl.audience, ...
        'notes',       tmpl.notes);

    url = sprintf('%s/api/projects/%s/reports', BASE_URL, pid);
    try
        resp = webwrite(url, payload, postOpts);
        projectReportCount = projectReportCount + 1;
        fprintf('  [%d/%d] Project report: %-50s  id=%s\n', ...
            i, nProjReports, payload.title, string(resp.report_id));
    catch ME
        fprintf('  [%d/%d] FAILED: %-50s  %s\n', i, nProjReports, payload.title, ME.message);
    end
end

% 3b. Standalone reports (POST /api/reports/generate)
standaloneTemplates = { ...
    struct('title', 'Q2 2026 Quantum Computing Lab Summary', ...
           'format', 'pdf', 'report_type', 'executive', ...
           'sections', {{'summary', 'comparison'}}, ...
           'audience', 'Lab Director', ...
           'notes', 'Quarterly summary of all quantum computing experiments and key results.'); ...
    struct('title', 'Backend Performance Comparison — April 2026', ...
           'format', 'pdf', 'report_type', 'technical', ...
           'sections', {{'summary', 'comparison', 'results'}}, ...
           'audience', 'Hardware Team', ...
           'notes', 'Comparative analysis of IBM Brisbane, Sherbrooke, Kyoto, and Osaka backends.'); ...
    struct('title', 'Error Mitigation Techniques Overview', ...
           'format', 'html', 'report_type', 'technical', ...
           'sections', {{'summary', 'features', 'results'}}, ...
           'audience', 'Research Team', ...
           'notes', 'Survey of ZNE, readout calibration, and dynamical decoupling effectiveness.'); ...
    struct('title', 'Transpilation Strategy Evaluation', ...
           'format', 'json', 'report_type', 'technical', ...
           'sections', {{'summary', 'comparison'}}, ...
           'audience', 'Software Team', ...
           'notes', 'Machine-readable report of transpiler strategy benchmarks across circuit types.'); ...
    struct('title', 'Annual Research Highlights 2026', ...
           'format', 'pdf', 'report_type', 'executive', ...
           'sections', {{'summary'}}, ...
           'audience', 'Board of Directors', ...
           'notes', 'Annual highlights of quantum computing research achievements.'); ...
};

standaloneCount = 0;
generateUrl = [BASE_URL '/api/reports/generate'];

for i = 1:numel(standaloneTemplates)
    tmpl = standaloneTemplates{i};

    payload = struct( ...
        'title',       tmpl.title, ...
        'report_type', tmpl.report_type, ...
        'format',      tmpl.format, ...
        'sections',    {tmpl.sections}, ...
        'audience',    tmpl.audience, ...
        'notes',       tmpl.notes);

    % Attach a job_record_id if available
    if i <= numel(jobIds)
        payload.job_record_id = jobIds{i};
    end

    try
        resp = webwrite(generateUrl, payload, postOpts);
        standaloneCount = standaloneCount + 1;
        fprintf('  Standalone: %-55s  id=%s\n', tmpl.title, string(resp.report_id));
    catch ME
        fprintf('  Standalone FAILED: %-50s  %s\n', tmpl.title, ME.message);
    end
end

fprintf('\n=== Done: %d project + %d standalone reports generated ===\n\n', ...
    projectReportCount, standaloneCount);
