% seed_projects.m ──────────────────────────────────────────────────────────────
% Creates 20 sample projects via the QTAU Connector REST API.
%
% Usage:
%   1. From the project root:
%        >> run('scripts/seed_projects.m')
%   2. Or from MATLAB with scripts/ as cwd:
%        >> seed_projects
%
% Prerequisites:
%   - The FastAPI backend must be reachable (default http://34.42.87.190:5715)
%   - Valid credentials (default sqkadmin / sqkadmin)
%
% Each project gets a random name, description, and 1-3 tags drawn from a
% shared pool so that 2-3 projects naturally share the same tag.
% ──────────────────────────────────────────────────────────────────────────────

fprintf('\n=== QTAU Seed: Creating 20 sample projects ===\n\n');

% ── Configuration ────────────────────────────────────────────────────────────
BASE_URL  = 'http://localhost:5715';
LOGIN_PATH = '/api/auth/login';
USERNAME  = 'admin';
PASSWORD  = 'passw0rd';

% ── Step 1: Authenticate ────────────────────────────────────────────────────
fprintf('[1/3] Logging in as "%s" ... ', USERNAME);
loginUrl = [BASE_URL LOGIN_PATH];
try
    import matlab.net.http.*
    import matlab.net.http.field.*
    import matlab.net.http.io.*
    body = FormProvider('username', USERNAME, 'password', PASSWORD);
    req  = RequestMessage('POST', ...
        [ContentTypeField(MediaType('application/x-www-form-urlencoded'))], body);
    resp = req.send(matlab.net.URI(loginUrl));
    if resp.StatusCode ~= 200
        error('Login failed with status %d: %s', resp.StatusCode, char(resp.Body.Data));
    end
    loginData = resp.Body.Data;
    token = string(loginData.access_token);
    fprintf('OK (token received)\n');
catch ME
    fprintf('FAILED\n  %s\n', ME.message);
    return;
end

% ── Step 2: Define seed data ─────────────────────────────────────────────────
fprintf('[2/3] Preparing seed data ...\n');

% Tag pool — small enough that 2-3 projects will share tags naturally
tagPool = { ...
    'fidelity', 'calibration', 'noise-model', 'error-mitigation', ...
    'transpilation', '27-qubit', '127-qubit', '433-qubit', ...
    'benchmarking', 'variational', 'grover', 'qft', ...
    'production', 'experimental', 'research'};

% Project templates — quantum computing research flavour
projectNames = { ...
    'BV-27 Fidelity Benchmark', ...
    'GHZ State Characterization', ...
    'Grover Search 5-Qubit Demo', ...
    'QFT Performance Analysis', ...
    'QAOA MaxCut Optimization', ...
    'VQE H2 Molecular Simulation', ...
    'Error Mitigation Comparison', ...
    'Noise Model Validation Suite', ...
    'Transpiler Strategy Eval', ...
    'Eagle r3 Calibration Run', ...
    'Heron Processor Baseline', ...
    'Cross-Resonance Gate Study', ...
    'Randomized Benchmarking v2', ...
    'Quantum Volume Measurement', ...
    'CLOPS Throughput Test', ...
    'Dynamical Decoupling Sweep', ...
    'Pauli Twirling Experiment', ...
    'ZNE Extrapolation Trial', ...
    'Readout Error Mitigation', ...
    'Multi-Qubit Entanglement Map'};

projectDescs = { ...
    'Evaluate Bernstein-Vazirani 27-qubit circuit fidelity across IBM Quantum backends with 4096 shots per configuration.', ...
    'Prepare and verify GHZ states on 5, 10, and 20 qubits to measure entanglement quality and decoherence rates.', ...
    'Benchmark Grover search oracle with 5 qubits, comparing transpilation levels 0-3 on ibm_sherbrooke.', ...
    'Profile Quantum Fourier Transform circuits from 4 to 20 qubits, tracking gate count and execution time.', ...
    'Run QAOA for MaxCut on random 3-regular graphs up to 12 nodes, sweeping depth from 1 to 5.', ...
    'Variational Quantum Eigensolver for H2 molecule at bond lengths 0.3-2.5 angstrom using UCCSD ansatz.', ...
    'Compare zero-noise extrapolation, probabilistic error cancellation, and M3 readout mitigation on real hardware.', ...
    'Validate the extended noise model against experimental data from ibm_brisbane and ibm_osaka backends.', ...
    'Evaluate Qiskit transpiler strategies (stochastic, sabre, dense) for circuit depth and two-qubit gate count.', ...
    'Full calibration characterization of Eagle r3 processor including T1, T2, gate fidelities, and crosstalk.', ...
    'Establish baseline performance metrics for the new Heron processor family across standard benchmark circuits.', ...
    'Detailed study of cross-resonance gate parameters and their impact on two-qubit gate fidelity.', ...
    'Run simultaneous and isolated single-qubit randomized benchmarking to extract average gate fidelities.', ...
    'Determine quantum volume using the standard protocol with 100 random circuits per qubit count.', ...
    'Measure Circuit Layer Operations Per Second (CLOPS) across different backend configurations.', ...
    'Sweep dynamical decoupling sequences (XY4, CPMG, Uhrig) to find optimal noise suppression schedules.', ...
    'Apply Pauli twirling to CNOT gates and measure the impact on overall circuit fidelity improvement.', ...
    'Zero-noise extrapolation with linear, polynomial, and exponential fits on 10-qubit random circuits.', ...
    'Characterize and mitigate readout assignment errors using calibration matrices and M3 framework.', ...
    'Map multi-qubit entanglement across the full 127-qubit heavy-hex topology to identify optimal qubit subsets.'};

% ── Step 3: Fetch existing projects to avoid duplicates ─────────────────────
fprintf('[3/4] Checking for existing projects ... ');
getOpts = weboptions('Timeout', 30, 'ContentType', 'json', ...
    'HeaderFields', {'Authorization', char("Bearer " + token)});
existingNames = {};
try
    projResp = webread([BASE_URL '/api/admin/projects?skip=0&limit=100'], getOpts);
    if isstruct(projResp) && isfield(projResp, 'projects')
        for k = 1:numel(projResp.projects)
            existingNames{end+1} = string(projResp.projects(k).name); %#ok<SAGROW>
        end
    end
    fprintf('found %d existing\n', numel(existingNames));
catch
    fprintf('(could not check — will attempt all)\n');
end

% ── Step 4: Create projects ──────────────────────────────────────────────────
fprintf('[4/4] Creating projects ...\n');

createUrl = [BASE_URL '/api/projects'];
opts = weboptions( ...
    'Timeout', 30, ...
    'MediaType', 'application/json', ...
    'ContentType', 'json', ...
    'HeaderFields', {'Authorization', char("Bearer " + token)});

successCount = 0;
skipCount    = 0;
for i = 1:20
    % Skip if project already exists
    if any(strcmp(existingNames, projectNames{i}))
        skipCount = skipCount + 1;
        fprintf('  [%2d/20] SKIP:    %s  (already exists)\n', i, projectNames{i});
        continue;
    end

    % Pick 1-3 random tags from the pool
    nTags = randi([1 3]);
    idx = randperm(numel(tagPool), nTags);
    tags = tagPool(idx);

    payload = struct( ...
        'name',        projectNames{i}, ...
        'description', projectDescs{i}, ...
        'tags',        {tags});

    try
        resp = webwrite(createUrl, payload, opts);
        successCount = successCount + 1;
        fprintf('  [%2d/20] Created: %s  (tags: %s)\n', i, projectNames{i}, strjoin(tags, ', '));
    catch ME
        fprintf('  [%2d/20] FAILED:  %s — %s\n', i, projectNames{i}, ME.message);
    end
end

fprintf('\n=== Done: %d created, %d skipped (existing) out of 20 ===\n\n', successCount, skipCount);
