% seed_notes.m ─────────────────────────────────────────────────────────────────
% Saves rich markdown notes with checklists for every project.
%
% Usage:
%   >> run('scripts/seed_notes.m')
%
% Provides data for: Notes screen (markdown editor + checklist panel)
% Prerequisites: seed_projects.m (projects must exist)
% ──────────────────────────────────────────────────────────────────────────────

fprintf('\n=== QTAU Seed: Saving notes for projects ===\n\n');

% ── Configuration ────────────────────────────────────────────────────────────
BASE_URL   = 'http://34.42.87.190:5715';
LOGIN_PATH = '/api/auth/login';
USERNAME   = 'admin';
PASSWORD   = 'passw0rd';

% ── Step 1: Authenticate ────────────────────────────────────────────────────
fprintf('[1/3] Logging in as "%s" ... ', USERNAME);
try
    import matlab.net.http.*
    import matlab.net.http.field.*
    import matlab.net.http.io.*
    body = FormProvider('username', USERNAME, 'password', PASSWORD);
    req  = RequestMessage('POST', ...
        [ContentTypeField(MediaType('application/x-www-form-urlencoded'))], body);
    resp = req.send(matlab.net.URI([BASE_URL LOGIN_PATH]));
    if resp.StatusCode ~= 200
        error('Login failed with status %d', int32(resp.StatusCode));
    end
    token = string(resp.Body.Data.access_token);
    fprintf('OK\n');
catch ME
    fprintf('FAILED\n  %s\n', ME.message);
    return;
end

authHeader = {'Authorization', char("Bearer " + token); 'Accept', 'application/json'};
getOpts = weboptions('Timeout', 30, 'ContentType', 'json', 'HeaderFields', authHeader);
putOpts = weboptions('Timeout', 30, 'MediaType', 'application/json', ...
    'ContentType', 'json', 'RequestMethod', 'put', 'HeaderFields', authHeader);

% ── Step 2: Fetch projects ───────────────────────────────────────────────────
fprintf('[2/3] Fetching projects ... ');
try
    projResp = webread([BASE_URL '/api/projects'], getOpts);
    projects = projResp.projects;
    nProj    = numel(projects);
    fprintf('found %d\n', nProj);
catch ME
    fprintf('FAILED (%s)\n', ME.message); return;
end

if nProj == 0
    fprintf('  No projects found. Run seed_projects.m first.\n');
    return;
end

% ── Step 3: Save notes ───────────────────────────────────────────────────────
fprintf('[3/3] Saving notes and checklists ...\n');

% Note templates — rich markdown with project-relevant content
noteTemplates = { ...
% Template 1: Fidelity benchmark
struct('notes', sprintf([ ...
    '## Experiment Log\n\n' ...
    '### Objective\n' ...
    'Evaluate circuit fidelity across multiple IBM Quantum backends.\n\n' ...
    '### Methodology\n' ...
    '- Run 4096 shots per configuration\n' ...
    '- Compare optimization levels 0-3\n' ...
    '- Measure against ideal simulator baseline\n\n' ...
    '### Key Observations\n' ...
    '- ibm_brisbane shows consistent 93-95%% fidelity for 5-qubit circuits\n' ...
    '- Optimization level 3 improves 2Q gate count by ~20%%\n' ...
    '- Readout error mitigation adds +1.5%% fidelity on average\n\n' ...
    '### Next Steps\n' ...
    '1. Extend to 10-qubit circuits\n' ...
    '2. Test dynamical decoupling sequences\n' ...
    '3. Compare with zero-noise extrapolation\n']), ...
    'checklist', {{ ...
        struct('item', 'IBM Quantum credentials verified',    'checked', true); ...
        struct('item', 'Circuit uploaded and validated',      'checked', true); ...
        struct('item', 'Backend selected and confirmed',      'checked', true); ...
        struct('item', 'Benchmark configuration saved',       'checked', true); ...
        struct('item', 'Prediction reviewed and accepted',    'checked', false); ...
        struct('item', 'Job submitted to hardware',           'checked', false); ...
        struct('item', 'Results reviewed and validated',      'checked', false); ...
        struct('item', 'Report generated and distributed',    'checked', false); ...
    }}), ...
% Template 2: State characterization
struct('notes', sprintf([ ...
    '## GHZ / Entanglement Study\n\n' ...
    '### Goal\n' ...
    'Prepare and verify GHZ states to measure entanglement quality.\n\n' ...
    '### Protocol\n' ...
    '- Prepare |GHZ_n> for n = 4, 8, 12\n' ...
    '- Measure in Z-basis and X-basis\n' ...
    '- Compute entanglement witness expectation value\n\n' ...
    '### Results So Far\n' ...
    '- 4-qubit GHZ: witness = 0.72 (>0.5 threshold)\n' ...
    '- 8-qubit GHZ: witness = 0.61 (marginal)\n' ...
    '- 12-qubit: pending hardware access\n']), ...
    'checklist', {{ ...
        struct('item', 'Credentials valid and token active',  'checked', true); ...
        struct('item', 'GHZ circuits uploaded (4,8,12 qubit)','checked', true); ...
        struct('item', 'Backend analysis complete',           'checked', false); ...
        struct('item', 'Benchmark run with error mitigation', 'checked', false); ...
        struct('item', 'Prediction confidence > 90%%',        'checked', false); ...
        struct('item', 'Hardware jobs submitted',             'checked', false); ...
        struct('item', 'Entanglement witness computed',       'checked', false); ...
        struct('item', 'Final report generated',              'checked', false); ...
    }}), ...
% Template 3: Algorithm benchmark
struct('notes', sprintf([ ...
    '## Algorithm Performance Tracking\n\n' ...
    '### Circuit Details\n' ...
    '- Type: Variational / QAOA / QFT\n' ...
    '- Qubit count: 4-6\n' ...
    '- Target depth after transpilation: < 50\n\n' ...
    '### Hardware Configuration\n' ...
    '- Backend: ibm_sherbrooke (127 qubits)\n' ...
    '- Shots: 4096\n' ...
    '- Error mitigation: readout calibration\n\n' ...
    '### Performance Metrics\n' ...
    '| Metric | Target | Actual |\n' ...
    '|--------|--------|--------|\n' ...
    '| Fidelity | >90%% | TBD |\n' ...
    '| Success prob | >85%% | TBD |\n' ...
    '| Queue time | <15 min | TBD |\n']), ...
    'checklist', {{ ...
        struct('item', 'Authentication configured',           'checked', true); ...
        struct('item', 'Circuit designed and uploaded',       'checked', true); ...
        struct('item', 'Feature analysis reviewed',           'checked', true); ...
        struct('item', 'Backend selected (primary + backup)', 'checked', false); ...
        struct('item', 'Transpilation strategy chosen',       'checked', false); ...
        struct('item', 'Job queued on IBM Quantum',           'checked', false); ...
        struct('item', 'Results match prediction within CI',  'checked', false); ...
        struct('item', 'Report shared with team',             'checked', false); ...
    }}), ...
% Template 4: Noise study
struct('notes', sprintf([ ...
    '## Noise Characterization Notes\n\n' ...
    '### Objective\n' ...
    'Systematic noise profiling of target backend.\n\n' ...
    '### Error Sources Under Investigation\n' ...
    '1. **Gate errors**: single-qubit (~0.1%%) and two-qubit (~1%%)\n' ...
    '2. **Readout errors**: assignment matrix characterization\n' ...
    '3. **Decoherence**: T1/T2 time measurements\n' ...
    '4. **Crosstalk**: simultaneous gate interference\n\n' ...
    '### Mitigation Strategies\n' ...
    '- Readout error mitigation (M3 framework)\n' ...
    '- Zero-noise extrapolation (linear + exponential)\n' ...
    '- Pauli twirling for 2Q gates\n' ...
    '- Dynamical decoupling (XY4 sequence)\n']), ...
    'checklist', {{ ...
        struct('item', 'API connection verified',             'checked', true); ...
        struct('item', 'Calibration data retrieved',          'checked', true); ...
        struct('item', 'RB circuits prepared',                'checked', false); ...
        struct('item', 'Tomography circuits uploaded',        'checked', false); ...
        struct('item', 'Crosstalk measurement designed',      'checked', false); ...
        struct('item', 'All experiments submitted',           'checked', false); ...
        struct('item', 'Noise model fitted',                  'checked', false); ...
        struct('item', 'Validation report complete',          'checked', false); ...
    }}), ...
% Template 5: Quick setup
struct('notes', sprintf([ ...
    '## Quick Start Checklist\n\n' ...
    'Use this project as a template for new experiments.\n\n' ...
    '### Getting Started\n' ...
    '1. Upload your QASM circuit via the Upload tab\n' ...
    '2. Review extracted features in Analysis\n' ...
    '3. Compare backends and select primary/backup\n' ...
    '4. Configure benchmark parameters\n' ...
    '5. Review prediction before submitting\n' ...
    '6. Monitor job in the Jobs tab\n' ...
    '7. Analyze results and generate report\n\n' ...
    '### Tips\n' ...
    '- Use optimization level 2 for best depth/fidelity trade-off\n' ...
    '- Enable readout calibration for circuits < 10 qubits\n' ...
    '- Check backend calibration age — prefer < 24 hours\n']), ...
    'checklist', {{ ...
        struct('item', 'Login with IBM Quantum credentials',  'checked', true); ...
        struct('item', 'Circuit uploaded successfully',       'checked', false); ...
        struct('item', 'Analysis features look reasonable',   'checked', false); ...
        struct('item', 'Backend with best fidelity selected', 'checked', false); ...
        struct('item', 'Benchmark parameters configured',     'checked', false); ...
        struct('item', 'Prediction reviewed',                 'checked', false); ...
        struct('item', 'Job completed without errors',        'checked', false); ...
        struct('item', 'Report generated',                    'checked', false); ...
    }}), ...
};

successCount = 0;
for i = 1:nProj
    proj = projects(i);
    pid  = string(proj.project_id);
    name = string(proj.name);

    tmplIdx = mod(i - 1, numel(noteTemplates)) + 1;
    tmpl    = noteTemplates{tmplIdx};

    checklistArray = tmpl.checklist;
    payload = struct('working_notes', tmpl.notes, 'checklist', {checklistArray});

    url = sprintf('%s/api/projects/%s/notes', BASE_URL, char(pid));
    try
        webwrite(url, payload, putOpts);
        successCount = successCount + 1;
        fprintf('  [%2d/%d] Notes saved: %-40s  (%d checklist items)\n', ...
            i, nProj, name, numel(checklistArray));
    catch ME
        fprintf('  [%2d/%d] FAILED:     %-40s  %s\n', i, nProj, name, ME.message);
    end
end

fprintf('\n=== Done: %d / %d project notes saved ===\n\n', successCount, nProj);
