% seed_circuits.m ──────────────────────────────────────────────────────────────
% Uploads 10 sample OpenQASM 2.0 circuits via the QTAU Connector REST API.
%
% Usage:
%   >> run('scripts/seed_circuits.m')
%
% Provides data for: Upload screen, Analysis screen
% Downstream: seed_benchmarks, seed_predictions, seed_jobs depend on these
% ──────────────────────────────────────────────────────────────────────────────

fprintf('\n=== QTAU Seed: Uploading 10 sample circuits ===\n\n');

% ── Configuration ────────────────────────────────────────────────────────────
BASE_URL   = 'http://34.42.87.190:5715';
LOGIN_PATH = '/api/auth/login';
USERNAME   = 'admin';
PASSWORD   = 'passw0rd';

% ── Step 1: Authenticate ────────────────────────────────────────────────────
fprintf('[1/3] Logging in as "%s" ... ', USERNAME);
try
    import matlab.net.http.*
    import matlab.net.http.field.*
    import matlab.net.http.io.*
    body = FormProvider('username', USERNAME, 'password', PASSWORD);
    req  = RequestMessage('POST', ...
        [ContentTypeField(MediaType('application/x-www-form-urlencoded'))], body);
    resp = req.send(matlab.net.URI([BASE_URL LOGIN_PATH]));
    if resp.StatusCode ~= 200
        error('Login failed with status %d', int32(resp.StatusCode));
    end
    token = string(resp.Body.Data.access_token);
    fprintf('OK\n');
catch ME
    fprintf('FAILED\n  %s\n', ME.message);
    return;
end

% ── Step 2: Define circuits ──────────────────────────────────────────────────
fprintf('[2/3] Preparing circuit data ...\n');

circuits = { ...
% ── 1. Bell State (2 qubits) ────────────────────────────────────────────────
struct( ...
    'name', 'bell_state_2q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Entanglement', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[2];\n' ...
        'creg c[2];\n' ...
        'h q[0];\n' ...
        'cx q[0],q[1];\n' ...
        'measure q[0] -> c[0];\n' ...
        'measure q[1] -> c[1];\n'])), ...
% ── 2. GHZ State (4 qubits) ─────────────────────────────────────────────────
struct( ...
    'name', 'ghz_state_4q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Entanglement', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[4];\n' ...
        'creg c[4];\n' ...
        'h q[0];\n' ...
        'cx q[0],q[1];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[2],q[3];\n' ...
        'measure q[0] -> c[0];\n' ...
        'measure q[1] -> c[1];\n' ...
        'measure q[2] -> c[2];\n' ...
        'measure q[3] -> c[3];\n'])), ...
% ── 3. QFT (4 qubits) ───────────────────────────────────────────────────────
struct( ...
    'name', 'qft_4q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Fourier', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[4];\n' ...
        'creg c[4];\n' ...
        'h q[0];\n' ...
        'cu1(pi/2) q[1],q[0];\n' ...
        'cu1(pi/4) q[2],q[0];\n' ...
        'cu1(pi/8) q[3],q[0];\n' ...
        'h q[1];\n' ...
        'cu1(pi/2) q[2],q[1];\n' ...
        'cu1(pi/4) q[3],q[1];\n' ...
        'h q[2];\n' ...
        'cu1(pi/2) q[3],q[2];\n' ...
        'h q[3];\n' ...
        'measure q -> c;\n'])), ...
% ── 4. Grover 3-qubit ────────────────────────────────────────────────────────
struct( ...
    'name', 'grover_3q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Search', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[3];\n' ...
        'creg c[3];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'x q[2];\n' ...
        'ccx q[0],q[1],q[2];\n' ...
        'x q[2];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'x q[0];\n' ...
        'x q[1];\n' ...
        'x q[2];\n' ...
        'ccx q[0],q[1],q[2];\n' ...
        'x q[0];\n' ...
        'x q[1];\n' ...
        'x q[2];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'measure q -> c;\n'])), ...
% ── 5. Bernstein-Vazirani (5 qubits) ────────────────────────────────────────
struct( ...
    'name', 'bernstein_vazirani_5q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Oracle', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[5];\n' ...
        'creg c[4];\n' ...
        'x q[4];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'h q[3];\n' ...
        'h q[4];\n' ...
        'cx q[0],q[4];\n' ...
        'cx q[1],q[4];\n' ...
        'cx q[3],q[4];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'h q[3];\n' ...
        'measure q[0] -> c[0];\n' ...
        'measure q[1] -> c[1];\n' ...
        'measure q[2] -> c[2];\n' ...
        'measure q[3] -> c[3];\n'])), ...
% ── 6. Quantum Teleportation (3 qubits) ─────────────────────────────────────
struct( ...
    'name', 'teleportation_3q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Entanglement', ...
    'source', 'custom', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[3];\n' ...
        'creg c0[1];\n' ...
        'creg c1[1];\n' ...
        'creg c2[1];\n' ...
        'h q[1];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[0],q[1];\n' ...
        'h q[0];\n' ...
        'measure q[0] -> c0[0];\n' ...
        'measure q[1] -> c1[0];\n'])), ...
% ── 7. Deutsch-Jozsa (4 qubits) ─────────────────────────────────────────────
struct( ...
    'name', 'deutsch_jozsa_4q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Oracle', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[4];\n' ...
        'creg c[3];\n' ...
        'x q[3];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'h q[3];\n' ...
        'cx q[0],q[3];\n' ...
        'cx q[1],q[3];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'measure q[0] -> c[0];\n' ...
        'measure q[1] -> c[1];\n' ...
        'measure q[2] -> c[2];\n'])), ...
% ── 8. VQE ansatz (4 qubits) ────────────────────────────────────────────────
struct( ...
    'name', 'vqe_ansatz_4q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Simulation', ...
    'source', 'custom', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[4];\n' ...
        'creg c[4];\n' ...
        'ry(0.5) q[0];\n' ...
        'ry(0.8) q[1];\n' ...
        'ry(1.2) q[2];\n' ...
        'ry(0.3) q[3];\n' ...
        'cx q[0],q[1];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[2],q[3];\n' ...
        'ry(0.7) q[0];\n' ...
        'ry(1.1) q[1];\n' ...
        'ry(0.4) q[2];\n' ...
        'ry(0.9) q[3];\n' ...
        'cx q[0],q[1];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[2],q[3];\n' ...
        'measure q -> c;\n'])), ...
% ── 9. QAOA MaxCut (6 qubits) ───────────────────────────────────────────────
struct( ...
    'name', 'qaoa_maxcut_6q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Optimization', ...
    'source', 'custom', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[6];\n' ...
        'creg c[6];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'h q[3];\n' ...
        'h q[4];\n' ...
        'h q[5];\n' ...
        'cx q[0],q[1];\n' ...
        'rz(0.6) q[1];\n' ...
        'cx q[0],q[1];\n' ...
        'cx q[1],q[2];\n' ...
        'rz(0.6) q[2];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[2],q[3];\n' ...
        'rz(0.6) q[3];\n' ...
        'cx q[2],q[3];\n' ...
        'cx q[3],q[4];\n' ...
        'rz(0.6) q[4];\n' ...
        'cx q[3],q[4];\n' ...
        'cx q[4],q[5];\n' ...
        'rz(0.6) q[5];\n' ...
        'cx q[4],q[5];\n' ...
        'rx(0.8) q[0];\n' ...
        'rx(0.8) q[1];\n' ...
        'rx(0.8) q[2];\n' ...
        'rx(0.8) q[3];\n' ...
        'rx(0.8) q[4];\n' ...
        'rx(0.8) q[5];\n' ...
        'measure q -> c;\n'])), ...
% ── 10. Random Benchmarking (5 qubits) ──────────────────────────────────────
struct( ...
    'name', 'random_bench_5q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Sampling', ...
    'source', 'MQTBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[5];\n' ...
        'creg c[5];\n' ...
        'h q[0];\n' ...
        'h q[2];\n' ...
        'h q[4];\n' ...
        'cx q[0],q[1];\n' ...
        'cx q[2],q[3];\n' ...
        't q[1];\n' ...
        't q[3];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[3],q[4];\n' ...
        's q[0];\n' ...
        'h q[0];\n' ...
        'cx q[0],q[1];\n' ...
        'h q[4];\n' ...
        'cx q[3],q[4];\n' ...
        'measure q -> c;\n'])) ...
};

% ── Step 3: Upload circuits ──────────────────────────────────────────────────
fprintf('[3/3] Uploading 10 circuits ...\n');

uploadUrl = [BASE_URL '/api/circuits/upload'];
opts = weboptions( ...
    'Timeout',      30, ...
    'MediaType',    'application/json', ...
    'ContentType',  'json', ...
    'HeaderFields', {'Authorization', char("Bearer " + token)});

successCount = 0;
circuitIds   = {};

for i = 1:numel(circuits)
    circ = circuits{i};
    try
        resp = webwrite(uploadUrl, circ, opts);
        cid = string(resp.circuit_id);
        circuitIds{end+1} = cid; %#ok<SAGROW>
        successCount = successCount + 1;
        fprintf('  [%2d/10] Uploaded: %-35s  id=%s\n', i, circ.name, cid);
    catch ME
        fprintf('  [%2d/10] FAILED:  %-35s  %s\n', i, circ.name, ME.message);
    end
end

fprintf('\n=== Done: %d / 10 circuits uploaded ===\n', successCount);
if ~isempty(circuitIds)
    fprintf('Circuit IDs available in workspace variable "circuitIds"\n\n');
end
