% seed_circuits.m ──────────────────────────────────────────────────────────────
% Uploads 10 sample OpenQASM 2.0 circuits via the QTAU Connector REST API.
%
% Usage:
%   >> run('scripts/seed_circuits.m')
%
% Provides data for: Upload screen, Analysis screen
% Downstream: seed_benchmarks, seed_predictions, seed_jobs depend on these
% ──────────────────────────────────────────────────────────────────────────────

fprintf('\n=== QTAU Seed: Uploading 10 sample circuits ===\n\n');

% ── Configuration ────────────────────────────────────────────────────────────
cfg      = seed_helpers.loadConfig();
BASE_URL = cfg.base_url;

% ── Step 1: Authenticate ────────────────────────────────────────────────────
fprintf('[1/4] Logging in as "%s" ... ', cfg.username);
try
    token = seed_helpers.login(BASE_URL, cfg.login_path, cfg.username, cfg.password);
    fprintf('OK\n');
catch ME
    fprintf('FAILED\n  %s\n', ME.message);
    return;
end

% ── Step 2: Define circuits ──────────────────────────────────────────────────
fprintf('[2/4] Preparing circuit data ...\n');

circuits = { ...
% ── 1. Bell State (2 qubits) ────────────────────────────────────────────────
struct( ...
    'name', 'bell_state_2q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Entanglement', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[2];\n' ...
        'creg c[2];\n' ...
        'h q[0];\n' ...
        'cx q[0],q[1];\n' ...
        'measure q[0] -> c[0];\n' ...
        'measure q[1] -> c[1];\n'])), ...
% ── 2. GHZ State (4 qubits) ─────────────────────────────────────────────────
struct( ...
    'name', 'ghz_state_4q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Entanglement', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[4];\n' ...
        'creg c[4];\n' ...
        'h q[0];\n' ...
        'cx q[0],q[1];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[2],q[3];\n' ...
        'measure q[0] -> c[0];\n' ...
        'measure q[1] -> c[1];\n' ...
        'measure q[2] -> c[2];\n' ...
        'measure q[3] -> c[3];\n'])), ...
% ── 3. QFT (4 qubits) ───────────────────────────────────────────────────────
struct( ...
    'name', 'qft_4q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Fourier', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[4];\n' ...
        'creg c[4];\n' ...
        'h q[0];\n' ...
        'cu1(pi/2) q[1],q[0];\n' ...
        'cu1(pi/4) q[2],q[0];\n' ...
        'cu1(pi/8) q[3],q[0];\n' ...
        'h q[1];\n' ...
        'cu1(pi/2) q[2],q[1];\n' ...
        'cu1(pi/4) q[3],q[1];\n' ...
        'h q[2];\n' ...
        'cu1(pi/2) q[3],q[2];\n' ...
        'h q[3];\n' ...
        'measure q -> c;\n'])), ...
% ── 4. Grover 3-qubit ────────────────────────────────────────────────────────
struct( ...
    'name', 'grover_3q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Search', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[3];\n' ...
        'creg c[3];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'x q[2];\n' ...
        'ccx q[0],q[1],q[2];\n' ...
        'x q[2];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'x q[0];\n' ...
        'x q[1];\n' ...
        'x q[2];\n' ...
        'ccx q[0],q[1],q[2];\n' ...
        'x q[0];\n' ...
        'x q[1];\n' ...
        'x q[2];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'measure q -> c;\n'])), ...
% ── 5. Bernstein-Vazirani (5 qubits) ────────────────────────────────────────
struct( ...
    'name', 'bernstein_vazirani_5q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Oracle', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[5];\n' ...
        'creg c[4];\n' ...
        'x q[4];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'h q[3];\n' ...
        'h q[4];\n' ...
        'cx q[0],q[4];\n' ...
        'cx q[1],q[4];\n' ...
        'cx q[3],q[4];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'h q[3];\n' ...
        'measure q[0] -> c[0];\n' ...
        'measure q[1] -> c[1];\n' ...
        'measure q[2] -> c[2];\n' ...
        'measure q[3] -> c[3];\n'])), ...
% ── 6. Quantum Teleportation (3 qubits) ─────────────────────────────────────
struct( ...
    'name', 'teleportation_3q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Entanglement', ...
    'source', 'custom', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[3];\n' ...
        'creg c0[1];\n' ...
        'creg c1[1];\n' ...
        'creg c2[1];\n' ...
        'h q[1];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[0],q[1];\n' ...
        'h q[0];\n' ...
        'measure q[0] -> c0[0];\n' ...
        'measure q[1] -> c1[0];\n'])), ...
% ── 7. Deutsch-Jozsa (4 qubits) ─────────────────────────────────────────────
struct( ...
    'name', 'deutsch_jozsa_4q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Oracle', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[4];\n' ...
        'creg c[3];\n' ...
        'x q[3];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'h q[3];\n' ...
        'cx q[0],q[3];\n' ...
        'cx q[1],q[3];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'measure q[0] -> c[0];\n' ...
        'measure q[1] -> c[1];\n' ...
        'measure q[2] -> c[2];\n'])), ...
% ── 8. VQE ansatz (4 qubits) ────────────────────────────────────────────────
struct( ...
    'name', 'vqe_ansatz_4q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Simulation', ...
    'source', 'custom', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[4];\n' ...
        'creg c[4];\n' ...
        'ry(0.5) q[0];\n' ...
        'ry(0.8) q[1];\n' ...
        'ry(1.2) q[2];\n' ...
        'ry(0.3) q[3];\n' ...
        'cx q[0],q[1];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[2],q[3];\n' ...
        'ry(0.7) q[0];\n' ...
        'ry(1.1) q[1];\n' ...
        'ry(0.4) q[2];\n' ...
        'ry(0.9) q[3];\n' ...
        'cx q[0],q[1];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[2],q[3];\n' ...
        'measure q -> c;\n'])), ...
% ── 9. QAOA MaxCut (6 qubits) ───────────────────────────────────────────────
struct( ...
    'name', 'qaoa_maxcut_6q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Optimization', ...
    'source', 'custom', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[6];\n' ...
        'creg c[6];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'h q[3];\n' ...
        'h q[4];\n' ...
        'h q[5];\n' ...
        'cx q[0],q[1];\n' ...
        'rz(0.6) q[1];\n' ...
        'cx q[0],q[1];\n' ...
        'cx q[1],q[2];\n' ...
        'rz(0.6) q[2];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[2],q[3];\n' ...
        'rz(0.6) q[3];\n' ...
        'cx q[2],q[3];\n' ...
        'cx q[3],q[4];\n' ...
        'rz(0.6) q[4];\n' ...
        'cx q[3],q[4];\n' ...
        'cx q[4],q[5];\n' ...
        'rz(0.6) q[5];\n' ...
        'cx q[4],q[5];\n' ...
        'rx(0.8) q[0];\n' ...
        'rx(0.8) q[1];\n' ...
        'rx(0.8) q[2];\n' ...
        'rx(0.8) q[3];\n' ...
        'rx(0.8) q[4];\n' ...
        'rx(0.8) q[5];\n' ...
        'measure q -> c;\n'])), ...
% ── 10. Random Benchmarking (5 qubits) ──────────────────────────────────────
struct( ...
    'name', 'random_bench_5q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Sampling', ...
    'source', 'MQTBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[5];\n' ...
        'creg c[5];\n' ...
        'h q[0];\n' ...
        'h q[2];\n' ...
        'h q[4];\n' ...
        'cx q[0],q[1];\n' ...
        'cx q[2],q[3];\n' ...
        't q[1];\n' ...
        't q[3];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[3],q[4];\n' ...
        's q[0];\n' ...
        'h q[0];\n' ...
        'cx q[0],q[1];\n' ...
        'h q[4];\n' ...
        'cx q[3],q[4];\n' ...
        'measure q -> c;\n'])) ...
};

% ── Step 3: Delete existing circuits (re-upload ensures fresh validation) ────
fprintf('[3/4] Deleting existing circuits ... ');
getOpts = seed_helpers.getOpts(token);
deleteOpts = weboptions('Timeout', 30, 'RequestMethod', 'delete', ...
    'HeaderFields', {'Authorization', char("Bearer " + token)});
deleteCount = 0;
try
    circResp = webread([BASE_URL '/api/circuits'], getOpts);
    if isstruct(circResp) && isfield(circResp, 'circuits')
        items = circResp.circuits;
    else
        items = circResp;
    end
    for k = 1:numel(items)
        try
            delUrl = sprintf('%s/api/circuits/%s', BASE_URL, char(string(items(k).circuit_id)));
            webread(delUrl, deleteOpts);
            deleteCount = deleteCount + 1;
        catch
            % 204 No Content is expected; ignore errors
            deleteCount = deleteCount + 1;
        end
    end
    fprintf('deleted %d\n', deleteCount);
catch
    fprintf('(none found or could not check)\n');
end

% ── Step 4: Upload circuits ──────────────────────────────────────────────────
fprintf('[4/4] Uploading circuits ...\n');

uploadUrl = [BASE_URL '/api/circuits/upload'];
opts = seed_helpers.postOpts(token);

successCount = 0;
circuitIds   = {};

for i = 1:numel(circuits)
    circ = circuits{i};

    try
        resp = webwrite(uploadUrl, circ, opts);
        cid = string(resp.circuit_id);
        circuitIds{end+1} = cid; %#ok<SAGROW>
        successCount = successCount + 1;
        valid = 'valid';
        if isfield(resp, 'is_valid') && ~resp.is_valid
            valid = 'INVALID';
        end
        fprintf('  [%2d/10] Uploaded: %-35s  id=%s  (%s)\n', i, circ.name, cid, valid);
    catch ME
        fprintf('  [%2d/10] FAILED:  %-35s  %s\n', i, circ.name, ME.message);
    end
end

fprintf('\n=== Done: %d uploaded out of 10 ===\n', successCount);
if ~isempty(circuitIds)
    fprintf('Circuit IDs available in workspace variable "circuitIds"\n\n');
end
