% seed_circuits.m ──────────────────────────────────────────────────────────────
% Uploads 10 sample OpenQASM 2.0 circuits to every project via the QTAU
% Connector REST API. Each upload is scoped to its project with the
% `X-Project-Id` request header so /api/circuits returns the circuits
% regardless of which project is active.
%
% Usage:
%   >> run('scripts/seed_circuits.m')
%
% Provides data for: Upload screen, Analysis screen, Circuits screen
% Prerequisite : seed_projects.m (projects must exist)
% Downstream   : seed_benchmarks, seed_predictions, seed_jobs
% ──────────────────────────────────────────────────────────────────────────────

fprintf('\n=== QTAU Seed: Uploading 10 sample circuits to every project ===\n\n');

% ── Configuration ────────────────────────────────────────────────────────────
cfg      = seed_helpers.loadConfig();
BASE_URL = cfg.base_url;

% ── Step 1: Authenticate ────────────────────────────────────────────────────
fprintf('[1/5] Logging in as "%s" ... ', cfg.username);
try
    token = seed_helpers.login(BASE_URL, cfg.login_path, cfg.username, cfg.password);
    fprintf('OK\n');
catch ME
    fprintf('FAILED\n  %s\n', ME.message);
    return;
end

% ── Step 2: Fetch projects ───────────────────────────────────────────────────
fprintf('[2/5] Fetching projects ... ');
getOpts = seed_helpers.getOpts(token);
try
    projResp = webread([BASE_URL '/api/projects'], getOpts);
    if isstruct(projResp) && isfield(projResp, 'projects')
        projects = projResp.projects;
    else
        projects = projResp;
    end
    nProj = numel(projects);
    fprintf('found %d projects\n', nProj);
catch ME
    fprintf('FAILED (%s)\n', ME.message);
    return;
end
if nProj == 0
    fprintf('  No projects found. Run seed_projects.m first.\n');
    return;
end

% ── Step 3: Define circuits ──────────────────────────────────────────────────
fprintf('[3/5] Preparing circuit data ...\n');

circuits = { ...
% ── 1. Bell State (2 qubits) ────────────────────────────────────────────────
struct( ...
    'name', 'bell_state_2q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Entanglement', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[2];\n' ...
        'creg c[2];\n' ...
        'h q[0];\n' ...
        'cx q[0],q[1];\n' ...
        'measure q[0] -> c[0];\n' ...
        'measure q[1] -> c[1];\n'])), ...
% ── 2. GHZ State (4 qubits) ─────────────────────────────────────────────────
struct( ...
    'name', 'ghz_state_4q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Entanglement', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[4];\n' ...
        'creg c[4];\n' ...
        'h q[0];\n' ...
        'cx q[0],q[1];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[2],q[3];\n' ...
        'measure q[0] -> c[0];\n' ...
        'measure q[1] -> c[1];\n' ...
        'measure q[2] -> c[2];\n' ...
        'measure q[3] -> c[3];\n'])), ...
% ── 3. QFT (4 qubits) ───────────────────────────────────────────────────────
struct( ...
    'name', 'qft_4q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Fourier', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[4];\n' ...
        'creg c[4];\n' ...
        'h q[0];\n' ...
        'cu1(pi/2) q[1],q[0];\n' ...
        'cu1(pi/4) q[2],q[0];\n' ...
        'cu1(pi/8) q[3],q[0];\n' ...
        'h q[1];\n' ...
        'cu1(pi/2) q[2],q[1];\n' ...
        'cu1(pi/4) q[3],q[1];\n' ...
        'h q[2];\n' ...
        'cu1(pi/2) q[3],q[2];\n' ...
        'h q[3];\n' ...
        'measure q -> c;\n'])), ...
% ── 4. Grover 3-qubit ────────────────────────────────────────────────────────
struct( ...
    'name', 'grover_3q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Search', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[3];\n' ...
        'creg c[3];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'x q[2];\n' ...
        'ccx q[0],q[1],q[2];\n' ...
        'x q[2];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'x q[0];\n' ...
        'x q[1];\n' ...
        'x q[2];\n' ...
        'ccx q[0],q[1],q[2];\n' ...
        'x q[0];\n' ...
        'x q[1];\n' ...
        'x q[2];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'measure q -> c;\n'])), ...
% ── 5. Bernstein-Vazirani (5 qubits) ────────────────────────────────────────
struct( ...
    'name', 'bernstein_vazirani_5q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Oracle', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[5];\n' ...
        'creg c[4];\n' ...
        'x q[4];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'h q[3];\n' ...
        'h q[4];\n' ...
        'cx q[0],q[4];\n' ...
        'cx q[1],q[4];\n' ...
        'cx q[3],q[4];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'h q[3];\n' ...
        'measure q[0] -> c[0];\n' ...
        'measure q[1] -> c[1];\n' ...
        'measure q[2] -> c[2];\n' ...
        'measure q[3] -> c[3];\n'])), ...
% ── 6. Quantum Teleportation (3 qubits) ─────────────────────────────────────
struct( ...
    'name', 'teleportation_3q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Entanglement', ...
    'source', 'custom', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[3];\n' ...
        'creg c0[1];\n' ...
        'creg c1[1];\n' ...
        'creg c2[1];\n' ...
        'h q[1];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[0],q[1];\n' ...
        'h q[0];\n' ...
        'measure q[0] -> c0[0];\n' ...
        'measure q[1] -> c1[0];\n'])), ...
% ── 7. Deutsch-Jozsa (4 qubits) ─────────────────────────────────────────────
struct( ...
    'name', 'deutsch_jozsa_4q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Oracle', ...
    'source', 'QASMBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[4];\n' ...
        'creg c[3];\n' ...
        'x q[3];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'h q[3];\n' ...
        'cx q[0],q[3];\n' ...
        'cx q[1],q[3];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'measure q[0] -> c[0];\n' ...
        'measure q[1] -> c[1];\n' ...
        'measure q[2] -> c[2];\n'])), ...
% ── 8. VQE ansatz (4 qubits) ────────────────────────────────────────────────
struct( ...
    'name', 'vqe_ansatz_4q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Simulation', ...
    'source', 'custom', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[4];\n' ...
        'creg c[4];\n' ...
        'ry(0.5) q[0];\n' ...
        'ry(0.8) q[1];\n' ...
        'ry(1.2) q[2];\n' ...
        'ry(0.3) q[3];\n' ...
        'cx q[0],q[1];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[2],q[3];\n' ...
        'ry(0.7) q[0];\n' ...
        'ry(1.1) q[1];\n' ...
        'ry(0.4) q[2];\n' ...
        'ry(0.9) q[3];\n' ...
        'cx q[0],q[1];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[2],q[3];\n' ...
        'measure q -> c;\n'])), ...
% ── 9. QAOA MaxCut (6 qubits) ───────────────────────────────────────────────
struct( ...
    'name', 'qaoa_maxcut_6q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Optimization', ...
    'source', 'custom', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[6];\n' ...
        'creg c[6];\n' ...
        'h q[0];\n' ...
        'h q[1];\n' ...
        'h q[2];\n' ...
        'h q[3];\n' ...
        'h q[4];\n' ...
        'h q[5];\n' ...
        'cx q[0],q[1];\n' ...
        'rz(0.6) q[1];\n' ...
        'cx q[0],q[1];\n' ...
        'cx q[1],q[2];\n' ...
        'rz(0.6) q[2];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[2],q[3];\n' ...
        'rz(0.6) q[3];\n' ...
        'cx q[2],q[3];\n' ...
        'cx q[3],q[4];\n' ...
        'rz(0.6) q[4];\n' ...
        'cx q[3],q[4];\n' ...
        'cx q[4],q[5];\n' ...
        'rz(0.6) q[5];\n' ...
        'cx q[4],q[5];\n' ...
        'rx(0.8) q[0];\n' ...
        'rx(0.8) q[1];\n' ...
        'rx(0.8) q[2];\n' ...
        'rx(0.8) q[3];\n' ...
        'rx(0.8) q[4];\n' ...
        'rx(0.8) q[5];\n' ...
        'measure q -> c;\n'])), ...
% ── 10. Random Benchmarking (5 qubits) ──────────────────────────────────────
struct( ...
    'name', 'random_bench_5q.qasm', ...
    'format', 'qasm2', ...
    'category', 'Sampling', ...
    'source', 'MQTBench', ...
    'content', sprintf([ ...
        'OPENQASM 2.0;\n' ...
        'include "qelib1.inc";\n' ...
        'qreg q[5];\n' ...
        'creg c[5];\n' ...
        'h q[0];\n' ...
        'h q[2];\n' ...
        'h q[4];\n' ...
        'cx q[0],q[1];\n' ...
        'cx q[2],q[3];\n' ...
        't q[1];\n' ...
        't q[3];\n' ...
        'cx q[1],q[2];\n' ...
        'cx q[3],q[4];\n' ...
        's q[0];\n' ...
        'h q[0];\n' ...
        'cx q[0],q[1];\n' ...
        'h q[4];\n' ...
        'cx q[3],q[4];\n' ...
        'measure q -> c;\n'])) ...
};

% ── Step 4: Clear existing circuits and upload per-project ───────────────────
fprintf('[4/5] Clearing existing circuits per project ...\n');

uploadUrl = [BASE_URL '/api/circuits/upload'];
authHdr   = {'Authorization', char("Bearer " + token); ...
             'Accept',        'application/json'};

projectDeleteCount = 0;
for p = 1:nProj
    pid  = char(string(projects(p).project_id));
    name = char(string(projects(p).name));

    projGetOpts = weboptions('Timeout', 30, 'ContentType', 'json', ...
        'HeaderFields', [authHdr; {'X-Project-Id', pid}]);
    projDelOpts = weboptions('Timeout', 30, 'RequestMethod', 'delete', ...
        'HeaderFields', [authHdr; {'X-Project-Id', pid}]);

    try
        circResp = webread([BASE_URL '/api/circuits'], projGetOpts);
        if isstruct(circResp) && isfield(circResp, 'circuits')
            items = circResp.circuits;
        else
            items = circResp;
        end
        nDel = 0;
        for k = 1:numel(items)
            try
                delUrl = sprintf('%s/api/circuits/%s', BASE_URL, ...
                    char(string(items(k).circuit_id)));
                webread(delUrl, projDelOpts);
            catch
                % 204 No Content is expected; ignore errors
            end
            nDel = nDel + 1;
        end
        projectDeleteCount = projectDeleteCount + nDel;
        fprintf('  [%2d/%d] %-40s  deleted %d\n', p, nProj, name, nDel);
    catch
        fprintf('  [%2d/%d] %-40s  (none / skipped)\n', p, nProj, name);
    end
end
fprintf('  → %d circuits deleted across all projects\n', projectDeleteCount);

% ── Step 5: Upload circuits into every project ──────────────────────────────
fprintf('[5/5] Uploading circuits into every project ...\n');

successCount = 0;
circuitIds   = {};

for p = 1:nProj
    pid  = char(string(projects(p).project_id));
    name = char(string(projects(p).name));

    opts = weboptions('Timeout', 30, ...
        'MediaType', 'application/json', 'ContentType', 'json', ...
        'HeaderFields', [authHdr; {'X-Project-Id', pid}]);

    projectSuccess = 0;
    for i = 1:numel(circuits)
        circ = circuits{i};
        try
            resp = webwrite(uploadUrl, circ, opts);
            cid  = string(resp.circuit_id);
            circuitIds{end+1} = cid; %#ok<SAGROW>
            projectSuccess = projectSuccess + 1;
            successCount   = successCount + 1;
        catch ME
            fprintf('    ! %-30s → %s\n', circ.name, ME.message);
        end
    end
    fprintf('  [%2d/%d] %-40s  uploaded %d/%d\n', ...
        p, nProj, name, projectSuccess, numel(circuits));
end

fprintf('\n=== Done: %d uploads across %d projects (10 circuits each) ===\n', ...
    successCount, nProj);
if ~isempty(circuitIds)
    fprintf('Circuit IDs available in workspace variable "circuitIds"\n\n');
end
